INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:00<00:20,  1.42it/s] 10%|█         | 3/30 [00:00<00:14,  1.92it/s] 13%|█▎        | 4/30 [00:01<00:14,  1.79it/s] 17%|█▋        | 5/30 [00:03<00:23,  1.06it/s] 20%|██        | 6/30 [00:03<00:16,  1.43it/s] 23%|██▎       | 7/30 [00:04<00:17,  1.30it/s] 27%|██▋       | 8/30 [00:04<00:12,  1.71it/s] 33%|███▎      | 10/30 [00:04<00:09,  2.20it/s] 40%|████      | 12/30 [00:04<00:06,  2.99it/s] 43%|████▎     | 13/30 [00:05<00:04,  3.45it/s] 47%|████▋     | 14/30 [00:05<00:04,  3.39it/s] 57%|█████▋    | 17/30 [00:05<00:02,  4.33it/s] 63%|██████▎   | 19/30 [00:05<00:01,  5.61it/s] 70%|███████   | 21/30 [00:06<00:02,  3.91it/s] 73%|███████▎  | 22/30 [00:08<00:04,  1.63it/s] 77%|███████▋  | 23/30 [00:10<00:07,  1.09s/it] 83%|████████▎ | 25/30 [00:10<00:03,  1.29it/s] 87%|████████▋ | 26/30 [00:11<00:03,  1.19it/s] 90%|█████████ | 27/30 [00:12<00:02,  1.03it/s] 97%|█████████▋| 29/30 [00:12<00:00,  1.43it/s]100%|██████████| 30/30 [00:12<00:00,  2.33it/s]
  0%|          | 0/164 [00:00<?, ?it/s]INFO:__main__:Requesting https://stockquanta.com
INFO:__main__:Getting metadata for https://www.stockquanta.com
  1%|          | 1/164 [00:00<02:41,  1.01it/s]INFO:__main__:Requesting https://coinquanta.com
INFO:__main__:Getting metadata for https://coinquanta.com
  1%|          | 2/164 [00:01<02:35,  1.04it/s]INFO:__main__:Requesting https://medium.com/mudrex/managing-risk-while-trading-4c14553fa143
INFO:__main__:Getting metadata for https://medium.com/mudrex/managing-risk-while-trading-4c14553fa143
  2%|▏         | 3/164 [00:02<02:17,  1.17it/s]INFO:__main__:Requesting https://www.blockchaintransparency.org/
INFO:__main__:Getting metadata for https://www.blockchaintransparency.org
  2%|▏         | 4/164 [00:03<02:13,  1.20it/s]INFO:__main__:Requesting https://medium.com/@kloudtrader/private-beta-and-kloudtrader-aural-c4a8561f70d0
INFO:__main__:Getting metadata for https://medium.com/@kloudtrader/private-beta-and-kloudtrader-aural-c4a8561f70d0
  3%|▎         | 5/164 [00:04<02:50,  1.07s/it]INFO:__main__:Requesting https://kloudtrader.com
INFO:__main__:Getting metadata for https://www.kloudtrader.com
  4%|▎         | 6/164 [00:05<02:49,  1.07s/it]INFO:__main__:Requesting https://medium.com/mudrex/tagged/learning
INFO:__main__:Getting metadata for https://medium.com/mudrex/tagged/learning
  4%|▍         | 7/164 [00:06<02:36,  1.00it/s]INFO:__main__:Requesting https://mudrex.com/indicators
INFO:__main__:Getting metadata for https://mudrex.com/indicators
  5%|▍         | 8/164 [00:07<02:24,  1.08it/s]INFO:__main__:Requesting https://github.com/gotify
INFO:__main__:Getting metadata for https://github.com/gotify
  5%|▌         | 9/164 [00:08<02:17,  1.13it/s]INFO:__main__:Requesting https://gotify.net/
INFO:__main__:Getting metadata for https://gotify.net
  6%|▌         | 10/164 [00:08<01:44,  1.47it/s]INFO:__main__:Requesting https://github.com/pirate/ArchiveBox
INFO:__main__:Getting metadata for https://github.com/pirate/ArchiveBox
  7%|▋         | 11/164 [00:09<01:55,  1.32it/s]INFO:__main__:Requesting https://launchaco.com
INFO:__main__:Getting metadata for https://www.launchaco.com
  7%|▋         | 12/164 [00:09<01:40,  1.51it/s]INFO:__main__:Requesting https://github.com/pirate/ArchiveBox/blob/a74d8410f4c3f2f08f75f223c15f8615be85744f/archivebox/archive_methods.py#L208
INFO:__main__:Getting metadata for https://github.com/pirate/ArchiveBox/blob/a74d8410f4c3f2f08f75f223c15f8615be85744f/archivebox/archive_methods.py#L208
  8%|▊         | 13/164 [00:10<01:56,  1.30it/s]INFO:__main__:Requesting https://github.com/webrecorder/pywb
INFO:__main__:Getting metadata for https://github.com/webrecorder/pywb
  9%|▊         | 14/164 [00:11<02:07,  1.18it/s]INFO:__main__:Requesting https://hackaday.com/2019/03/09/speedrunning-windows-95/
ERROR:__main__:Could not reach https://hackaday.com/2019/03/09/speedrunning-windows-95/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
  9%|▉         | 15/164 [00:12<01:34,  1.57it/s]INFO:__main__:Requesting https://mobile.twitter.com/Foone/status/1103384684812255233
INFO:__main__:Getting metadata for https://mobile.twitter.com/Foone/status/1103384684812255233
 10%|▉         | 16/164 [00:13<02:24,  1.02it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/NetBIOS_Frames_protocol
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/NetBIOS_Frames_protocol
 10%|█         | 17/164 [00:14<02:06,  1.16it/s]INFO:__main__:Requesting https://news.vice.com/en_us/article/7xakd9/windows-31-is-still-alive-and-it-just-killed-a-french-airport
INFO:__main__:Getting metadata for https://news.vice.com/en_us/article/7xakd9/windows-31-is-still-alive-and-it-just-killed-a-french-airport
 11%|█         | 18/164 [00:14<01:39,  1.47it/s]INFO:__main__:Requesting https://arstechnica.com/information-technology/2017/05/in-a-throwback-to-the-90s-ntfs-bug-lets-anyone-hang-or-crash-windows-7-8-1/
INFO:__main__:Getting metadata for https://arstechnica.com/information-technology/2017/05/in-a-throwback-to-the-90s-ntfs-bug-lets-anyone-hang-or-crash-windows-7-8-1/
 12%|█▏        | 19/164 [00:15<01:20,  1.80it/s]INFO:__main__:Requesting https://msfn.org/board/topic/141402-windows-95-21ghz-cpu-limit-broken/
INFO:__main__:Getting metadata for https://msfn.org/board/topic/141402-windows-95-21ghz-cpu-limit-broken/
 12%|█▏        | 20/164 [00:16<02:10,  1.10it/s]INFO:__main__:Requesting https://xkcd.com/284/
INFO:__main__:Getting metadata for https://xkcd.com/284/
 13%|█▎        | 21/164 [00:17<01:51,  1.29it/s]INFO:__main__:Requesting https://github.com/LiveSplit/LiveSplit/blob/master/Documentation/Auto-Splitters.md
INFO:__main__:Getting metadata for https://github.com/LiveSplit/LiveSplit/blob/master/Documentation/Auto-Splitters.md
 13%|█▎        | 22/164 [00:18<01:55,  1.23it/s]INFO:__main__:Requesting http://www.annoyances.org/
INFO:__main__:Getting metadata for http://www.annoyances.org
 14%|█▍        | 23/164 [00:18<01:29,  1.57it/s]INFO:__main__:Requesting https://www.litepc.com/
INFO:__main__:Getting metadata for https://www.litepc.com
 15%|█▍        | 24/164 [00:22<03:51,  1.66s/it]INFO:__main__:Requesting https://forums.virtualbox.org/viewtopic.php?t=82787
INFO:__main__:Getting metadata for https://forums.virtualbox.org/viewtopic.php?t=82787
 15%|█▌        | 25/164 [00:24<04:23,  1.90s/it]INFO:__main__:Requesting https://github.com/CypherpunkArmory/UserLAnd
INFO:__main__:Getting metadata for https://github.com/CypherpunkArmory/UserLAnd
 16%|█▌        | 26/164 [00:25<03:37,  1.58s/it]INFO:__main__:Requesting https://wiki.termux.com/wiki/Main_Page
INFO:__main__:Getting metadata for https://wiki.termux.com/wiki/Main_Page
 16%|█▋        | 27/164 [00:30<05:43,  2.50s/it]INFO:__main__:Requesting https://github.com/termux/termux-app
INFO:__main__:Getting metadata for https://github.com/termux/termux-app
 17%|█▋        | 28/164 [00:31<04:38,  2.05s/it]INFO:__main__:Requesting https://www.reddit.com/r/termux/
INFO:__main__:Getting metadata for https://www.reddit.com/r/termux/
 18%|█▊        | 29/164 [00:32<04:10,  1.86s/it]INFO:__main__:Requesting https://github.com/termux/termux-app/issues/954#issuecomment-448199494
INFO:__main__:Getting metadata for https://github.com/termux/termux-app/issues/954#issuecomment-448199494
 18%|█▊        | 30/164 [00:33<03:35,  1.61s/it]INFO:__main__:Requesting https://github.com/sp4rkie/debian-on-termux
INFO:__main__:Getting metadata for https://github.com/sp4rkie/debian-on-termux
 19%|█▉        | 31/164 [00:34<03:02,  1.37s/it]INFO:__main__:Requesting https://github.com/its-pointless/gcc_termux
INFO:__main__:Getting metadata for https://github.com/its-pointless/gcc_termux
 20%|█▉        | 32/164 [00:35<02:42,  1.23s/it]INFO:__main__:Requesting https://play.google.com/store/apps/details?id=org.connectbot
INFO:__main__:Getting metadata for https://play.google.com/store/apps/details?id=org.connectbot
 20%|██        | 33/164 [00:35<02:10,  1.00it/s]INFO:__main__:Requesting https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard
INFO:__main__:Getting metadata for https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard
 21%|██        | 34/164 [00:36<01:51,  1.17it/s]INFO:__main__:Requesting https://browser.geekbench.com/android_devices/839
INFO:__main__:Getting metadata for https://browser.geekbench.com/android_devices/839
 21%|██▏       | 35/164 [00:41<04:48,  2.24s/it]INFO:__main__:Requesting https://browser.geekbench.com/processors/2294
INFO:__main__:Getting metadata for https://browser.geekbench.com/processors/2294
 22%|██▏       | 36/164 [00:47<06:59,  3.28s/it]INFO:__main__:Requesting https://browser.geekbench.com/processors/763
INFO:__main__:Getting metadata for https://browser.geekbench.com/processors/763
 23%|██▎       | 37/164 [00:51<07:25,  3.51s/it]INFO:__main__:Requesting https://www.samsung.com/semiconductor/insights/tech-trends/emmc-to-ufs-how-nand-memory-for-mobile-products-is-evolving/
INFO:__main__:Getting metadata for https://www.samsung.com/semiconductor/insights/tech-trends/emmc-to-ufs-how-nand-memory-for-mobile-products-is-evolving/
 23%|██▎       | 38/164 [00:51<05:19,  2.54s/it]INFO:__main__:Requesting https://maruos.com
INFO:__main__:Getting metadata for https://maruos.com
 24%|██▍       | 39/164 [00:52<04:19,  2.07s/it]INFO:__main__:Requesting https://www.microsoft.com/en-gb/windows/continuum
INFO:__main__:Getting metadata for https://www.microsoft.com/en-gb/windows/continuum
 24%|██▍       | 40/164 [00:54<03:45,  1.82s/it]INFO:__main__:Requesting https://ubports.com/
INFO:__main__:Getting metadata for https://ubports.com
 25%|██▌       | 41/164 [00:56<04:07,  2.02s/it]INFO:__main__:Requesting https://github.com/louisdh/openterm
INFO:__main__:Getting metadata for https://github.com/louisdh/openterm
 26%|██▌       | 42/164 [00:57<03:25,  1.68s/it]INFO:__main__:Requesting https://github.com/ColdGrub1384/LibTerm/blob/master/README.md
INFO:__main__:Getting metadata for https://github.com/ColdGrub1384/LibTerm/blob/master/README.md
 26%|██▌       | 43/164 [00:58<03:02,  1.51s/it]INFO:__main__:Requesting https://github.com/tbodt/ish
INFO:__main__:Getting metadata for https://github.com/tbodt/ish
 27%|██▋       | 44/164 [00:59<02:42,  1.35s/it]INFO:__main__:Requesting https://github.com/fsquillace/junest
INFO:__main__:Getting metadata for https://github.com/fsquillace/junest
 27%|██▋       | 45/164 [01:00<02:25,  1.22s/it]INFO:__main__:Requesting https://liliputing.com/2018/07/gpd-pocket-2-preview.html
INFO:__main__:Getting metadata for https://liliputing.com/2018/07/gpd-pocket-2-preview.html
 28%|██▊       | 46/164 [01:00<01:51,  1.06it/s]INFO:__main__:Requesting https://github.com/termux/termux-packages/tree/master/packages
INFO:__main__:Getting metadata for https://github.com/termux/termux-packages/tree/master/packages
 29%|██▊       | 47/164 [01:02<02:28,  1.27s/it]INFO:__main__:Requesting https://blueoakcouncil.org/license/1.0.0
INFO:__main__:Getting metadata for https://blueoakcouncil.org/license/1.0.0
 29%|██▉       | 48/164 [01:03<01:52,  1.03it/s]INFO:__main__:Requesting https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html
INFO:__main__:Getting metadata for https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html
 30%|██▉       | 49/164 [01:03<01:32,  1.25it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/ISC_license
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/ISC_license
 30%|███       | 50/164 [01:04<01:34,  1.21it/s]INFO:__main__:Requesting https://www.reuters.com/article/us-netherlands-pharmaceuticals-insight-idUSKCN1QP0M4
INFO:__main__:Getting metadata for https://www.reuters.com/article/us-netherlands-pharmaceuticals-insight-idUSKCN1QP0M4
 31%|███       | 51/164 [01:04<01:16,  1.48it/s]INFO:__main__:Requesting https://nos.nl/artikel/2266712-hoe-nederlands-kankeronderzoek-novartis-aan-miljarden-gaat-helpen.html
INFO:__main__:Getting metadata for https://nos.nl/artikel/2266712-hoe-nederlands-kankeronderzoek-novartis-aan-miljarden-gaat-helpen.html
 32%|███▏      | 52/164 [01:05<01:29,  1.25it/s]INFO:__main__:Requesting http://sourceonhealthcare.org/orphan-drug-act-fostering-innovation-or-abuse/
INFO:__main__:Getting metadata for http://sourceonhealthcare.org/orphan-drug-act-fostering-innovation-or-abuse/
 32%|███▏      | 53/164 [01:06<01:35,  1.16it/s]INFO:__main__:Requesting https://philanthropynewsdigest.org/news/cystic-fibrosis-foundation-receives-3.3-billion-royalty-pay-out
INFO:__main__:Getting metadata for https://philanthropynewsdigest.org/news/cystic-fibrosis-foundation-receives-3.3-billion-royalty-pay-out
 33%|███▎      | 54/164 [01:07<01:27,  1.25it/s]INFO:__main__:Requesting https://www.kff.org/news-summary/india-brazil-launch-trade-dispute-against-eu-netherlands-over-seizures-of-generic-drugs/
ERROR:__main__:Could not reach https://www.kff.org/news-summary/india-brazil-launch-trade-dispute-against-eu-netherlands-over-seizures-of-generic-drugs/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 34%|███▎      | 55/164 [01:07<01:06,  1.64it/s]INFO:__main__:Requesting https://www.oncode.nl/research/programs
ERROR:__main__:Could not reach https://www.oncode.nl/research/programs
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.oncode.nl', port=443): Max retries exceeded with url: /research/programs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.oncode.nl', port=443): Max retries exceeded with url: /research/programs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
 34%|███▍      | 56/164 [01:08<01:00,  1.77it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/ISDS
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/ISDS
 35%|███▍      | 57/164 [01:09<01:24,  1.27it/s]INFO:__main__:Requesting https://github.com/DeanRoddey/CIDLib#cidlib---a-c-development-environment
INFO:__main__:Getting metadata for https://github.com/DeanRoddey/CIDLib#cidlib---a-c-development-environment
 35%|███▌      | 58/164 [01:10<01:22,  1.28it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Object_request_broker
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Object_request_broker
 36%|███▌      | 59/164 [01:10<01:16,  1.37it/s]INFO:__main__:Requesting https://pacman128.github.io/pcasm/
INFO:__main__:Getting metadata for https://pacman128.github.io/pcasm/
 37%|███▋      | 60/164 [01:11<01:04,  1.61it/s]INFO:__main__:Requesting https://github.com/tevador/RandomX
INFO:__main__:Getting metadata for https://github.com/tevador/RandomX
 37%|███▋      | 61/164 [01:12<01:10,  1.46it/s]INFO:__main__:Requesting https://ruderich.org/simon/notes/append-only-backups-with-restic-and-rclone
INFO:__main__:Getting metadata for https://ruderich.org/simon/notes/append-only-backups-with-restic-and-rclone
 38%|███▊      | 62/164 [01:14<02:08,  1.26s/it]INFO:__main__:Requesting http://www.squidi.net/three/index.php
 38%|███▊      | 63/164 [01:14<01:34,  1.07it/s]INFO:__main__:Requesting http://www.squidi.net/three/entry.php?id=207
 39%|███▉      | 64/164 [01:14<01:09,  1.44it/s]INFO:__main__:Requesting http://www.squidi.net/comic/amd/
 40%|███▉      | 65/164 [01:15<00:51,  1.93it/s]INFO:__main__:Requesting http://virt10.itu.chalmers.se/index.php
INFO:__main__:Getting metadata for http://virt10.itu.chalmers.se/index.php/Main_Page
 40%|████      | 66/164 [01:18<02:05,  1.28s/it]INFO:__main__:Requesting http://www.10zenmonkeys.com/2019/02/25/the-great-captain-marvel-soundtrack-scam/
INFO:__main__:Getting metadata for http://www.10zenmonkeys.com/2019/02/25/the-great-captain-marvel-soundtrack-scam/
 41%|████      | 67/164 [01:20<02:29,  1.54s/it]INFO:__main__:Requesting https://www.theverge.com/2019/1/21/18191332/spotify-block-feature-mute-artists-music
INFO:__main__:Getting metadata for https://www.theverge.com/2019/1/21/18191332/spotify-block-feature-mute-artists-music
 41%|████▏     | 68/164 [01:20<01:55,  1.21s/it]INFO:__main__:Requesting https://openreview.net/forum?id=H1xQVn09FX
INFO:__main__:Getting metadata for https://openreview.net/forum?id=H1xQVn09FX
 42%|████▏     | 69/164 [01:20<01:26,  1.10it/s]INFO:__main__:Requesting http://www.yosefk.com/blog/its-done-in-hardware-so-its-cheap.html
INFO:__main__:Getting metadata for http://yosefk.com/blog/its-done-in-hardware-so-its-cheap.html
 43%|████▎     | 70/164 [01:22<01:37,  1.04s/it]INFO:__main__:Requesting https://github.com/pjc50/ancient-3d-for-turboc
INFO:__main__:Getting metadata for https://github.com/pjc50/ancient-3d-for-turboc
 43%|████▎     | 71/164 [01:23<01:30,  1.02it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/3dfx_Interactive
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/3dfx_Interactive
 44%|████▍     | 72/164 [01:24<01:30,  1.02it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Silicon_Graphics
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Silicon_Graphics
 45%|████▍     | 73/164 [01:25<01:38,  1.09s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Cache_on_a_stick
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Cache_on_a_stick
 45%|████▌     | 74/164 [01:25<01:23,  1.07it/s]INFO:__main__:Requesting https://flyingkmachines.wordpress.com/
ERROR:__main__:Could not reach https://flyingkmachines.wordpress.com/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 46%|████▌     | 75/164 [01:26<01:01,  1.45it/s]INFO:__main__:Requesting https://www.sciencemag.org/news/2019/03/black-death-may-have-transformed-medieval-societies-sub-saharan-africa
INFO:__main__:Getting metadata for https://www.sciencemag.org/news/2019/03/black-death-may-have-transformed-medieval-societies-sub-saharan-africa
 46%|████▋     | 76/164 [01:26<00:55,  1.58it/s]INFO:__main__:Requesting https://medium.com/@niant/why-deadlines-and-sprints-are-bad-for-you-7ee87be5d0f0
INFO:__main__:Getting metadata for https://medium.com/@niant/why-deadlines-and-sprints-are-bad-for-you-7ee87be5d0f0
 47%|████▋     | 77/164 [01:26<00:49,  1.76it/s]INFO:__main__:Requesting https://apenwarr.ca/log/?m=201712
INFO:__main__:Getting metadata for https://apenwarr.ca/log/?m=201712
 48%|████▊     | 78/164 [01:29<01:38,  1.15s/it]INFO:__main__:Requesting https://www.scrum.org/resources/commitment-vs-forecast
INFO:__main__:Getting metadata for https://www.scrum.org/resources/commitment-vs-forecast
 48%|████▊     | 79/164 [01:30<01:21,  1.04it/s]INFO:__main__:Requesting https://www.linkedin.com/pulse/scrum-evening-james-coplien-vassilis-hardalias
INFO:__main__:Getting metadata for https://www.linkedin.com/pulse/scrum-evening-james-coplien-vassilis-hardalias
 49%|████▉     | 80/164 [01:30<01:12,  1.15it/s]INFO:__main__:Requesting http://www.bell-labs.com/usr/dmr/www/chist.html
INFO:__main__:Getting metadata for http://www.bell-labs.com/usr/dmr/www/chist.html
 49%|████▉     | 81/164 [01:31<01:16,  1.09it/s]INFO:__main__:Requesting https://www.theparisreview.org/blog/2019/03/05/dice-roll-the-phantom-gambler/
INFO:__main__:Getting metadata for https://www.theparisreview.org/blog/2019/03/05/dice-roll-the-phantom-gambler/
 50%|█████     | 82/164 [01:31<00:58,  1.41it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/William_Lee_Bergstrom
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/William_Lee_Bergstrom
 51%|█████     | 83/164 [01:32<00:54,  1.48it/s]INFO:__main__:Requesting https://www.edyoda.com/course/1227
INFO:__main__:Getting metadata for https://www.edyoda.com/course/1227
 51%|█████     | 84/164 [01:37<02:33,  1.92s/it]INFO:__main__:Requesting https://mathml.igalia.com/news/2019/02/12/launch-of-the-project/
INFO:__main__:Getting metadata for https://mathml.igalia.com/news/2019/02/12/launch-of-the-project/
 52%|█████▏    | 85/164 [01:39<02:45,  2.09s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/MathML#Example_and_comparison_to_other_formats
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/MathML#Example_and_comparison_to_other_formats
 52%|█████▏    | 86/164 [01:41<02:25,  1.86s/it]INFO:__main__:Requesting https://gist.github.com/aplaice/266b092bc48afbbdd46cdbd0ca811da8#file-quadratic-xml
INFO:__main__:Getting metadata for https://gist.github.com/aplaice/266b092bc48afbbdd46cdbd0ca811da8#file-quadratic-xml
 53%|█████▎    | 87/164 [01:41<01:52,  1.46s/it]INFO:__main__:Requesting http://fred-wang.github.io/MathUI2014/demos/7-web-component.html
INFO:__main__:Getting metadata for http://fred-wang.github.io/MathUI2014/demos/7-web-component.html
 54%|█████▎    | 88/164 [01:41<01:22,  1.08s/it]INFO:__main__:Requesting https://github.com/fred-wang/MathUI2014/blob/master/demos/7-web-component.html
INFO:__main__:Getting metadata for https://github.com/fred-wang/MathUI2014/blob/master/demos/7-web-component.html
 54%|█████▍    | 89/164 [01:42<01:13,  1.02it/s]INFO:__main__:Requesting https://github.com/fred-wang/x-tex
INFO:__main__:Getting metadata for https://github.com/fred-wang/x-tex
 55%|█████▍    | 90/164 [01:43<01:06,  1.11it/s]INFO:__main__:Requesting https://runarberg.github.io/ascii2mathml/
INFO:__main__:Getting metadata for https://runarberg.github.io/ascii2mathml/
 55%|█████▌    | 91/164 [01:44<01:04,  1.13it/s]INFO:__main__:Requesting http://docs.mathjax.org/en/latest/output.html
INFO:__main__:Getting metadata for http://docs.mathjax.org/en/latest/output.html
 56%|█████▌    | 92/164 [01:45<01:06,  1.08it/s]INFO:__main__:Requesting https://webkit.org/blog/6803/improvements-in-mathml-rendering/
INFO:__main__:Getting metadata for https://webkit.org/blog/6803/improvements-in-mathml-rendering/
 57%|█████▋    | 93/164 [01:45<00:57,  1.23it/s]INFO:__main__:Requesting https://standardebooks.org/ebooks/ludwig-wittgenstein/tractatus-logico-philosophicus/c-k-ogden
INFO:__main__:Getting metadata for https://standardebooks.org/ebooks/ludwig-wittgenstein/tractatus-logico-philosophicus/c-k-ogden
 57%|█████▋    | 94/164 [01:46<00:47,  1.48it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Help:Displaying_a_formula#Native_MathML
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Help:Displaying_a_formula#Native_MathML
 58%|█████▊    | 95/164 [01:52<02:54,  2.53s/it]INFO:__main__:Requesting http://www.w3.org/1998/Math/MathML">
INFO:__main__:Requesting http://fred-wang.github.io/MathUI2014/demos/2-mathml-in-svg.svg
INFO:__main__:Getting metadata for http://fred-wang.github.io/MathUI2014/demos/2-mathml-in-svg.svg
 59%|█████▉    | 97/164 [01:53<02:01,  1.82s/it]INFO:__main__:Requesting http://fred-wang.github.io/MathUI2014/demos/6-mathml-in-webgl.html
INFO:__main__:Getting metadata for http://fred-wang.github.io/MathUI2014/demos/6-mathml-in-webgl.html
 60%|█████▉    | 98/164 [01:53<01:27,  1.32s/it]INFO:__main__:Requesting https://www.mediawiki.org/wiki/Extension:Math/advancedSettings#CSS_for_the_MathML_with_SVG_fallback_mode
INFO:__main__:Getting metadata for https://www.mediawiki.org/wiki/Extension:Math/advancedSettings#CSS_for_the_MathML_with_SVG_fallback_mode
 60%|██████    | 99/164 [01:54<01:18,  1.21s/it]INFO:__main__:Requesting https://ncatlab.org/nlab/show/HomePage
INFO:__main__:Getting metadata for https://ncatlab.org/nlab/show/HomePage
 61%|██████    | 100/164 [01:55<01:18,  1.23s/it]INFO:__main__:Requesting https://arxiv.org/help/mathjax
INFO:__main__:Getting metadata for https://arxiv.org/help/mathjax
 62%|██████▏   | 101/164 [01:57<01:30,  1.44s/it]INFO:__main__:Requesting https://mdn.mozillademos.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test$samples/MathML_Torture_Test?revision=1449367
INFO:__main__:Getting metadata for https://mdn.mozillademos.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test$samples/MathML_Torture_Test?revision=1449367
 62%|██████▏   | 102/164 [01:59<01:36,  1.56s/it]INFO:__main__:Requesting https://bugs.chromium.org/p/chromium/issues/list?can=2&q=%22use+after+free%22&sort=&groupby=&colspec=&x=&y=&mode=&cells=&num=
ERROR:__main__:Could not reach https://bugs.chromium.org/p/chromium/issues/list?can=2&q=%22use+after+free%22&sort=&groupby=&colspec=&x=&y=&mode=&cells=&num=
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='bugs.chromium.org', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='bugs.chromium.org', port=443): Read timed out. (read timeout=6)
 63%|██████▎   | 103/164 [02:05<02:56,  2.90s/it]INFO:__main__:Requesting https://www.gwern.net/Embryo-selection
INFO:__main__:Getting metadata for https://www.gwern.net/Embryo-selection
 63%|██████▎   | 104/164 [02:10<03:39,  3.65s/it]INFO:__main__:Requesting https://github.com/Microsoft/reactxp
INFO:__main__:Getting metadata for https://github.com/Microsoft/reactxp
 64%|██████▍   | 105/164 [02:12<02:58,  3.02s/it]INFO:__main__:Requesting https://www.theatlantic.com/technology/archive/2019/03/china-has-stopped-accepting-our-trash/584131/
INFO:__main__:Getting metadata for https://www.theatlantic.com/technology/archive/2019/03/china-has-stopped-accepting-our-trash/584131/
 65%|██████▍   | 106/164 [02:12<02:06,  2.18s/it]INFO:__main__:Requesting https://www.bath.ac.uk/case-studies/debunking-big-tobaccos-arguments-against-standardised-packaging/
INFO:__main__:Getting metadata for https://www.bath.ac.uk/case-studies/debunking-big-tobaccos-arguments-against-standardised-packaging/
 65%|██████▌   | 107/164 [02:14<02:04,  2.19s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Dry_ice#Manufacture
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Dry_ice#Manufacture
 66%|██████▌   | 108/164 [02:15<01:42,  1.83s/it]INFO:__main__:Requesting https://www.thisiseco.co.uk/news_and_blog/what-happens-to-waste-to-energy-incineration-ash.html
INFO:__main__:Getting metadata for https://www.thisiseco.co.uk/news_and_blog/what-happens-to-waste-to-energy-incineration-ash.html
 66%|██████▋   | 109/164 [02:17<01:31,  1.66s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Green_Dot_(symbol)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Green_Dot_(symbol)
 67%|██████▋   | 110/164 [02:17<01:12,  1.34s/it]INFO:__main__:Requesting https://www.youtube.com/watch?time_continue=254&v=4FpsH_ETT7c
INFO:__main__:Getting metadata for https://www.youtube.com/watch?time_continue=254&v=4FpsH_ETT7c
 68%|██████▊   | 111/164 [02:18<01:05,  1.23s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=f0OZ7Mlmkvk
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=f0OZ7Mlmkvk
 68%|██████▊   | 112/164 [02:19<00:57,  1.10s/it]INFO:__main__:Requesting https://www.kcet.org/shows/socal-connected/carbonlite-inside-the-worlds-largest-plastic-bottle-recycling-plant-0
INFO:__main__:Getting metadata for https://www.kcet.org/shows/socal-connected/carbonlite-inside-the-worlds-largest-plastic-bottle-recycling-plant-0
 69%|██████▉   | 113/164 [02:20<00:50,  1.02it/s]INFO:__main__:Requesting https://www.wastedive.com/news/china-contamination-standard-MRFs/519659/
INFO:__main__:Getting metadata for https://www.wastedive.com/news/china-contamination-standard-MRFs/519659/
 70%|██████▉   | 114/164 [02:21<00:51,  1.02s/it]INFO:__main__:Requesting https://slate.com/business/2013/01/yacht-economics-rich-people-don-t-consume-very-much.html
INFO:__main__:Getting metadata for https://slate.com/business/2013/01/yacht-economics-rich-people-don-t-consume-very-much.html
 70%|███████   | 115/164 [02:21<00:42,  1.15it/s]INFO:__main__:Requesting https://www.dailymotion.com/video/x6klo0p
INFO:__main__:Getting metadata for https://www.dailymotion.com/video/x6klo0p
 71%|███████   | 116/164 [02:23<00:46,  1.03it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Mobro_4000
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Mobro_4000
 71%|███████▏  | 117/164 [02:23<00:43,  1.09it/s]INFO:__main__:Requesting https://www.plasticchina.org/
INFO:__main__:Getting metadata for https://www.plasticchina.org
 72%|███████▏  | 118/164 [02:28<01:27,  1.90s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Plasma_gasification
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Plasma_gasification
 73%|███████▎  | 119/164 [02:29<01:13,  1.63s/it]INFO:__main__:Requesting https://purecycletech.com/
INFO:__main__:Getting metadata for https://purecycletech.com
 73%|███████▎  | 120/164 [02:29<01:00,  1.37s/it]INFO:__main__:Requesting https://twitter.com/joeerl/status/1104298407231922176
INFO:__main__:Getting metadata for https://twitter.com/joeerl/status/1104298407231922176
 74%|███████▍  | 121/164 [02:30<00:53,  1.25s/it]INFO:__main__:Requesting http://paulgraham.com/pypar.html
INFO:__main__:Getting metadata for http://paulgraham.com/pypar.html
 74%|███████▍  | 122/164 [02:31<00:43,  1.03s/it]INFO:__main__:Requesting https://elixir-lang.org/getting-started/introduction.html
INFO:__main__:Getting metadata for https://elixir-lang.org/getting-started/introduction.html
 75%|███████▌  | 123/164 [02:31<00:31,  1.29it/s]INFO:__main__:Requesting https://github.com/elixirkoans/elixir-koans
INFO:__main__:Getting metadata for https://github.com/elixirkoans/elixir-koans
 76%|███████▌  | 124/164 [02:32<00:31,  1.29it/s]INFO:__main__:Requesting https://codestool.coding-gnome.com/courses/elixir-for-programmers
INFO:__main__:Getting metadata for https://codestool.coding-gnome.com/courses/elixir-for-programmers
 76%|███████▌  | 125/164 [02:33<00:31,  1.25it/s]INFO:__main__:Requesting https://thedailywtf.com/articles/A_Case_of_the_MUMPS
INFO:__main__:Getting metadata for https://thedailywtf.com/articles/A_Case_of_the_MUMPS
 77%|███████▋  | 126/164 [02:35<00:53,  1.41s/it]INFO:__main__:Requesting https://twitter.com/devoncestes/status/1104000439987683328
INFO:__main__:Getting metadata for https://twitter.com/devoncestes/status/1104000439987683328
 77%|███████▋  | 127/164 [02:36<00:47,  1.27s/it]INFO:__main__:Requesting http://paulgraham.com/avg.html
INFO:__main__:Getting metadata for http://paulgraham.com/avg.html
 78%|███████▊  | 128/164 [02:37<00:37,  1.05s/it]INFO:__main__:Requesting https://www.activestate.com/resources/webinars/perl-paradox/
INFO:__main__:Getting metadata for https://www.activestate.com/resources/webinars/perl-paradox/
 79%|███████▊  | 129/164 [02:37<00:31,  1.12it/s]INFO:__main__:Requesting https://twitter.com/guieevc/status/1002494428748140544
INFO:__main__:Getting metadata for https://twitter.com/guieevc/status/1002494428748140544
 79%|███████▉  | 130/164 [02:38<00:30,  1.12it/s]INFO:__main__:Requesting https://www.ericsson.com/en/news/2018/5/erlang-celebrates-20-years-as-open-source
INFO:__main__:Getting metadata for https://www.ericsson.com/en/news/2018/5/erlang-celebrates-20-years-as-open-source
 80%|███████▉  | 131/164 [02:39<00:26,  1.23it/s]INFO:__main__:Requesting https://jobs.ericsson.com/jobs?keywords=erlang&page=1
INFO:__main__:Getting metadata for https://jobs.ericsson.com/jobs?keywords=erlang&page=1
 80%|████████  | 132/164 [02:40<00:29,  1.08it/s]INFO:__main__:Requesting https://www.linkedin.com/jobs/view/master-thesis-erlang-json-for-the-5g-core-network-at-ericsson-958913296/?originalSubdomain=se
INFO:__main__:Requesting https://learnyousomeerlang.com/dialyzer
INFO:__main__:Getting metadata for https://learnyousomeerlang.com/dialyzer
 82%|████████▏ | 134/164 [02:42<00:27,  1.08it/s]INFO:__main__:Requesting http://wiki.c2.com/?SoftTyping
INFO:__main__:Getting metadata for http://wiki.c2.com/?SoftTyping
 82%|████████▏ | 135/164 [02:42<00:20,  1.40it/s]INFO:__main__:Requesting https://github.com/patriknw/akka-typed-blog/blob/master/src/main/java/blog/typed/javadsl/Greeter1.java
INFO:__main__:Getting metadata for https://github.com/patriknw/akka-typed-blog/blob/master/src/main/java/blog/typed/javadsl/Greeter1.java
 83%|████████▎ | 136/164 [02:43<00:19,  1.41it/s]INFO:__main__:Requesting https://www.jefftk.com/p/nomic-game-3
INFO:__main__:Getting metadata for https://www.jefftk.com/p/nomic-game-3
 84%|████████▎ | 137/164 [02:45<00:31,  1.16s/it]INFO:__main__:Requesting https://agoranomic.org
INFO:__main__:Getting metadata for https://agoranomic.org
 84%|████████▍ | 138/164 [02:46<00:27,  1.06s/it]INFO:__main__:Requesting https://latinamericareports.com/the-demolition-of-escobar-monaco-in-medellins-historical-memory
INFO:__main__:Getting metadata for https://latinamericareports.com/the-demolition-of-escobar-monaco-in-medellins-historical-memory/1294/
 85%|████████▍ | 139/164 [02:48<00:34,  1.36s/it]INFO:__main__:Requesting https://techcrunch.com/2019/03/08/tufts-grade-hacking/
ERROR:__main__:Could not reach https://techcrunch.com/2019/03/08/tufts-grade-hacking/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 85%|████████▌ | 140/164 [02:48<00:23,  1.01it/s]INFO:__main__:Requesting https://outline.com/ZTzSYa
INFO:__main__:Getting metadata for https://outline.com/ZTzSYa
 86%|████████▌ | 141/164 [02:49<00:23,  1.03s/it]INFO:__main__:Requesting https://youtu.be/0xVF7yCKWno?t=60
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=0xVF7yCKWno&feature=youtu.be&t=60
 87%|████████▋ | 142/164 [02:50<00:22,  1.01s/it]INFO:__main__:Requesting https://www.washingtonpost.com/nation/2018/11/16/his-ex-accused-him-an-attack-that-could-have-meant-life-prison-selfie-saved-him/
ERROR:__main__:Could not reach https://www.washingtonpost.com/nation/2018/11/16/his-ex-accused-him-an-attack-that-could-have-meant-life-prison-selfie-saved-him/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 210, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.washingtonpost.com', port=443): Read timed out. (read timeout=6)
 87%|████████▋ | 143/164 [02:56<00:53,  2.53s/it]INFO:__main__:Requesting https://www.bbc.com/news/science-environment-47478537
INFO:__main__:Getting metadata for https://www.bbc.com/news/science-environment-47478537
 88%|████████▊ | 144/164 [02:57<00:36,  1.84s/it]INFO:__main__:Requesting https://www.theguardian.com/science/2005/jan/18/educationsgendergap.genderissues
INFO:__main__:Getting metadata for https://www.theguardian.com/science/2005/jan/18/educationsgendergap.genderissues
 88%|████████▊ | 145/164 [02:57<00:25,  1.36s/it]INFO:__main__:Requesting http://www.smallpianokeyboards.org/uploads/3/4/1/6/34165129/right-hand-span-results-with-dots-dec-2016_1_orig.jpg
INFO:__main__:Getting metadata for http://www.smallpianokeyboards.org/uploads/3/4/1/6/34165129/right-hand-span-results-with-dots-dec-2016_1_orig.jpg
 89%|████████▉ | 146/164 [03:02<00:45,  2.56s/it]INFO:__main__:Requesting http://www.smallpianokeyboards.org/hand-span-data.html
INFO:__main__:Getting metadata for http://www.smallpianokeyboards.org/hand-span-data.html
 90%|████████▉ | 147/164 [03:03<00:32,  1.90s/it]INFO:__main__:Requesting https://press.cern/press-releases/2018/09/updated-statement-cern-stands-diversity*
 90%|█████████ | 148/164 [03:04<00:29,  1.84s/it]INFO:__main__:Requesting https://news.ycombinator.com/newsguidelines.html
INFO:__main__:Getting metadata for https://news.ycombinator.com/newsguidelines.html
 91%|█████████ | 149/164 [03:05<00:24,  1.62s/it]INFO:__main__:Requesting https://drive.google.com/file/d/1c_NyUhOZ8erdqU2AGZJZtNfFeA91Kefj/view
INFO:__main__:Getting metadata for https://drive.google.com/file/d/1c_NyUhOZ8erdqU2AGZJZtNfFeA91Kefj/view
 91%|█████████▏| 150/164 [03:07<00:24,  1.76s/it]INFO:__main__:Requesting https://www.splcenter.org/fighting-hate/intelligence-report/2002/ally-christian-right-heavyweight-paul-weyrich-addresses-holocaust-denial-conference
INFO:__main__:Getting metadata for https://www.splcenter.org/fighting-hate/intelligence-report/2002/ally-christian-right-heavyweight-paul-weyrich-addresses-holocaust-denial-conference
 92%|█████████▏| 151/164 [03:08<00:16,  1.30s/it]INFO:__main__:Requesting https://www.scottaaronson.com/blog/?p=304
 93%|█████████▎| 152/164 [03:08<00:12,  1.01s/it]INFO:__main__:Requesting http://resonaances.blogspot.com/2016/06/game-of-thrones-750-gev-edition.html
INFO:__main__:Getting metadata for http://resonaances.blogspot.com/2016/06/game-of-thrones-750-gev-edition.html
 93%|█████████▎| 153/164 [03:08<00:09,  1.20it/s]INFO:__main__:Requesting https://www.particlesforjustice.org
INFO:__main__:Getting metadata for https://www.particlesforjustice.org
 94%|█████████▍| 154/164 [03:09<00:07,  1.29it/s]INFO:__main__:Requesting https://justiceforstrumia.org
INFO:__main__:Getting metadata for https://justiceforstrumia.org
 95%|█████████▍| 155/164 [03:10<00:07,  1.26it/s]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Emmy_Noether
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Emmy_Noether
 95%|█████████▌| 156/164 [03:12<00:09,  1.18s/it]INFO:__main__:Requesting https://www.theguardian.com/education/2017/aug/28/university-gender-gap-at-record-high-as-30000-more-women-accepted
INFO:__main__:Getting metadata for https://www.theguardian.com/education/2017/aug/28/university-gender-gap-at-record-high-as-30000-more-women-accepted
 96%|█████████▌| 157/164 [03:12<00:06,  1.08it/s]INFO:__main__:Requesting https://www.hesa.ac.uk/news/11-01-2018/sfr247-higher-education-student-statistics/subjects
INFO:__main__:Getting metadata for https://www.hesa.ac.uk/news/11-01-2018/sfr247-higher-education-student-statistics/subjects
 96%|█████████▋| 158/164 [03:14<00:06,  1.06s/it]INFO:__main__:Requesting http://backreaction.blogspot.com/2018/10/gender-bias-in-academia-case-strumia.html?m=1
INFO:__main__:Getting metadata for http://backreaction.blogspot.com/2018/10/gender-bias-in-academia-case-strumia.html?m=1
 97%|█████████▋| 159/164 [03:14<00:04,  1.03it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/The_Emperor%27s_New_Clothes
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/The_Emperor%27s_New_Clothes
 98%|█████████▊| 160/164 [03:15<00:03,  1.03it/s]INFO:__main__:Requesting https://blog.granthika.co/panini/
INFO:__main__:Getting metadata for https://blog.granthika.co/panini/
 98%|█████████▊| 161/164 [03:16<00:02,  1.10it/s]INFO:__main__:Requesting http://gltr.io/
INFO:__main__:Getting metadata for http://gltr.io
 99%|█████████▉| 162/164 [03:16<00:01,  1.44it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Mojibake
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Mojibake
 99%|█████████▉| 163/164 [03:18<00:00,  1.04it/s]INFO:__main__:Requesting https://www.workable.com/j/089F60DE31
INFO:__main__:Getting metadata for https://jerry.workable.com/j/089F60DE31
100%|██████████| 164/164 [03:19<00:00,  1.10it/s]
