INFO:__main__:Get urls from stories
  0%|          | 0/30 [00:00<?, ?it/s]  3%|▎         | 1/30 [00:00<00:06,  4.25it/s]  7%|▋         | 2/30 [00:00<00:07,  3.74it/s] 10%|█         | 3/30 [00:01<00:13,  2.08it/s] 13%|█▎        | 4/30 [00:02<00:12,  2.01it/s] 17%|█▋        | 5/30 [00:02<00:13,  1.80it/s] 20%|██        | 6/30 [00:03<00:12,  1.92it/s] 23%|██▎       | 7/30 [00:03<00:11,  1.97it/s] 30%|███       | 9/30 [00:04<00:09,  2.31it/s] 33%|███▎      | 10/30 [00:04<00:07,  2.53it/s] 37%|███▋      | 11/30 [00:04<00:05,  3.21it/s] 40%|████      | 12/30 [00:04<00:05,  3.11it/s] 43%|████▎     | 13/30 [00:05<00:04,  3.92it/s] 47%|████▋     | 14/30 [00:05<00:03,  4.20it/s] 50%|█████     | 15/30 [00:05<00:04,  3.62it/s] 57%|█████▋    | 17/30 [00:06<00:03,  3.50it/s] 70%|███████   | 21/30 [00:07<00:02,  3.84it/s] 73%|███████▎  | 22/30 [00:07<00:01,  4.48it/s] 77%|███████▋  | 23/30 [00:09<00:05,  1.31it/s] 80%|████████  | 24/30 [00:09<00:03,  1.65it/s] 83%|████████▎ | 25/30 [00:09<00:02,  2.20it/s] 87%|████████▋ | 26/30 [00:12<00:04,  1.08s/it] 90%|█████████ | 27/30 [00:12<00:02,  1.23it/s] 93%|█████████▎| 28/30 [00:15<00:03,  1.61s/it] 97%|█████████▋| 29/30 [00:17<00:01,  1.61s/it]100%|██████████| 30/30 [00:17<00:00,  1.24s/it]
  0%|          | 0/284 [00:00<?, ?it/s]INFO:__main__:Requesting https://crazyoscarchang.github.io/2019/02/16/seven-myths-in-machine-learning-research/
INFO:__main__:Getting metadata for https://crazyoscarchang.github.io/2019/02/16/seven-myths-in-machine-learning-research/
  0%|          | 1/284 [00:00<01:55,  2.45it/s]INFO:__main__:Requesting https://blog.evjang.com/2019/02/bagnet.html
INFO:__main__:Getting metadata for https://blog.evjang.com/2019/02/bagnet.html
  1%|          | 2/284 [00:00<02:02,  2.30it/s]INFO:__main__:Requesting https://www.technologyreview.com/s/538111/why-and-how-baidu-cheated-an-artificial-intelligence-test/
INFO:__main__:Getting metadata for https://www.technologyreview.com/s/538111/why-and-how-baidu-cheated-an-artificial-intelligence-test/
  1%|          | 3/284 [00:01<02:17,  2.04it/s]INFO:__main__:Requesting http://hunch.net/?p=22
INFO:__main__:Getting metadata for http://hunch.net/?p=22
  1%|▏         | 4/284 [00:06<09:01,  1.93s/it]INFO:__main__:Requesting https://www.theguardian.com/technology/2013/aug/07/google-chrome-password-security-flaw
INFO:__main__:Getting metadata for https://www.theguardian.com/technology/2013/aug/07/google-chrome-password-security-flaw
  2%|▏         | 5/284 [00:07<06:55,  1.49s/it]INFO:__main__:Requesting https://arxiv.org/pdf/1711.02114.pdf);
INFO:__main__:Getting metadata for https://arxiv.org/pdf/1711.02114.pdf)
  2%|▏         | 6/284 [00:33<41:19,  8.92s/it]INFO:__main__:Requesting https://math.stackexchange.com/questions/412423/what-are-the-differences-between-a-matrix-and-a-tensor
INFO:__main__:Getting metadata for https://math.stackexchange.com/questions/412423/what-are-the-differences-between-a-matrix-and-a-tensor
  2%|▏         | 7/284 [00:33<29:27,  6.38s/it]INFO:__main__:Requesting https://nepis.epa.gov/Exe/ZyPDF.cgi/9101HEAX.PDF?Dockey=9101HEAX.PDF
INFO:__main__:Getting metadata for https://nepis.epa.gov/Exe/ZyPDF.cgi/9101HEAX.PDF?Dockey=9101HEAX.PDF
  3%|▎         | 8/284 [00:41<30:51,  6.71s/it]INFO:__main__:Requesting https://www.skepticalscience.com/climate-change-global-warming.htm
INFO:__main__:Getting metadata for https://www.skepticalscience.com/climate-change-global-warming.htm
  3%|▎         | 9/284 [00:43<24:18,  5.30s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Frank_Luntz#Global_warming
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Frank_Luntz#Global_warming
  4%|▎         | 10/284 [00:44<18:31,  4.06s/it]INFO:__main__:Requesting https://www.npr.org/2019/02/07/691997301/rep-alexandria-ocasio-cortez-releases-green-new-deal-outline
INFO:__main__:Getting metadata for https://www.npr.org/2019/02/07/691997301/rep-alexandria-ocasio-cortez-releases-green-new-deal-outline
  4%|▍         | 11/284 [00:44<13:17,  2.92s/it]INFO:__main__:Requesting https://apps.npr.org/documents/document.html?id=5729035-Green-New-Deal-FAQ
INFO:__main__:Getting metadata for https://apps.npr.org/documents/document.html?id=5729035-Green-New-Deal-FAQ
  4%|▍         | 12/284 [00:46<10:55,  2.41s/it]INFO:__main__:Requesting https://pmm.nasa.gov/education/articles/whats-name-global-warming-vs-climate-change
INFO:__main__:Getting metadata for https://pmm.nasa.gov/education/articles/whats-name-global-warming-vs-climate-change
  5%|▍         | 13/284 [00:47<09:53,  2.19s/it]INFO:__main__:Requesting https://www.skepticalscience.com/climate-change-global-warming.html
INFO:__main__:Getting metadata for https://www.skepticalscience.com/climate-change-global-warming.html
  5%|▍         | 14/284 [00:49<09:11,  2.04s/it]INFO:__main__:Requesting https://climate.nasa.gov/vital-signs/global-temperature/
INFO:__main__:Getting metadata for https://climate.nasa.gov/vital-signs/global-temperature/
  5%|▌         | 15/284 [00:50<08:08,  1.82s/it]INFO:__main__:Requesting https://www.nytimes.com/interactive/2018/08/01/magazine/climate-change-losing-earth.html
INFO:__main__:Getting metadata for https://www.nytimes.com/interactive/2018/08/01/magazine/climate-change-losing-earth.html
  6%|▌         | 16/284 [00:51<06:49,  1.53s/it]INFO:__main__:Requesting https://twitter.com/davelevitan/status/1100141281332940802?s=21
INFO:__main__:Getting metadata for https://twitter.com/davelevitan/status/1100141281332940802?s=21
  6%|▌         | 17/284 [00:52<06:05,  1.37s/it]INFO:__main__:Requesting https://www.talospace.com/2019/02/the-last-power1-on-mars-is-dead.html
INFO:__main__:Getting metadata for https://www.talospace.com/2019/02/the-last-power1-on-mars-is-dead.html
  6%|▋         | 18/284 [00:52<04:32,  1.02s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Intergalactic_Computer_Network
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Intergalactic_Computer_Network
  7%|▋         | 19/284 [00:53<04:11,  1.05it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/CCSDS_File_Delivery_Protocol
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/CCSDS_File_Delivery_Protocol
  7%|▋         | 20/284 [00:54<03:49,  1.15it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Rumi_calendar#/media/File:1911_Ottoman_Calendar.jpg
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Rumi_calendar#/media/File:1911_Ottoman_Calendar.jpg
  7%|▋         | 21/284 [00:55<04:07,  1.06it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Royal_Observatory,_Greenwich#Observatory_museum
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Royal_Observatory,_Greenwich#Observatory_museum
  8%|▊         | 22/284 [00:57<05:16,  1.21s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Proper_time
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Proper_time
  8%|▊         | 23/284 [00:58<05:42,  1.31s/it]INFO:__main__:Requesting http://www.jb.man.ac.uk/distance/frontiers/pulsars/section4.html
INFO:__main__:Getting metadata for http://www.jb.man.ac.uk/distance/frontiers/pulsars/section4.html
  8%|▊         | 24/284 [01:01<07:13,  1.67s/it]INFO:__main__:Requesting http://physicscentral.com/explore/writers/will.cfm
INFO:__main__:Getting metadata for http://physicscentral.com/explore/writers/will.cfm
  9%|▉         | 25/284 [01:01<05:22,  1.25s/it]INFO:__main__:Requesting https://space.stackexchange.com/questions/33590/time-dilation-between-mars-and-earth-due-to-different-mass
INFO:__main__:Getting metadata for https://space.stackexchange.com/questions/33590/time-dilation-between-mars-and-earth-due-to-different-mass
  9%|▉         | 26/284 [01:02<04:23,  1.02s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Pulsar#Precise_clocks
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Pulsar#Precise_clocks
 10%|▉         | 27/284 [01:04<05:37,  1.31s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Pulsar_clock
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Pulsar_clock
 10%|▉         | 28/284 [01:04<04:50,  1.13s/it]INFO:__main__:Requesting https://www.w3.org/TR/html52/textlevel-semantics.html#the-time-element
INFO:__main__:Getting metadata for https://www.w3.org/TR/html52/textlevel-semantics.html#the-time-element
 10%|█         | 29/284 [01:27<31:53,  7.51s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Barycentric_Coordinate_Time
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Barycentric_Coordinate_Time
 11%|█         | 30/284 [01:27<23:15,  5.50s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/International_System_of_Units#Base_units
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/International_System_of_Units#Base_units
 11%|█         | 31/284 [01:30<19:57,  4.73s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Swatch_Internet_Time
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Swatch_Internet_Time
 11%|█▏        | 32/284 [01:31<14:54,  3.55s/it]INFO:__main__:Requesting https://stackoverflow.com/questions/1024711/hidden-features-of-tcl-tk#comment838620_1026619
INFO:__main__:Getting metadata for https://stackoverflow.com/questions/1024711/hidden-features-of-tcl-tk#comment838620_1026619
 12%|█▏        | 33/284 [01:32<10:50,  2.59s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Stardate
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Stardate
 12%|█▏        | 34/284 [01:33<08:59,  2.16s/it]INFO:__main__:Requesting http://ops-alaska.com/time/gangale_mst/abstract.htm
ERROR:__main__:Could not reach http://ops-alaska.com/time/gangale_mst/abstract.htm
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f1c2b9ea208>, 'Connection to ops-alaska.com timed out. (connect timeout=6)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ops-alaska.com', port=80): Max retries exceeded with url: /time/gangale_mst/abstract.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1c2b9ea208>, 'Connection to ops-alaska.com timed out. (connect timeout=6)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 209, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='ops-alaska.com', port=80): Max retries exceeded with url: /time/gangale_mst/abstract.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1c2b9ea208>, 'Connection to ops-alaska.com timed out. (connect timeout=6)'))
 12%|█▏        | 35/284 [01:39<13:52,  3.34s/it]INFO:__main__:Requesting https://mars.nasa.gov/mer/mission/rover-status/opportunity/recent/all/
INFO:__main__:Getting metadata for https://mars.nasa.gov/mer/mission/rover-status/opportunity/recent/all/
 13%|█▎        | 36/284 [01:40<10:40,  2.58s/it]INFO:__main__:Requesting https://github.com/smacke/subsync
INFO:__main__:Getting metadata for https://github.com/smacke/subsync
 13%|█▎        | 37/284 [01:40<08:27,  2.06s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Convolution
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Convolution
 13%|█▎        | 38/284 [01:43<08:56,  2.18s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Convolution_theorem
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Convolution_theorem
 14%|█▎        | 39/284 [01:45<08:32,  2.09s/it]INFO:__main__:Requesting https://github.com/SubtitleEdit/subtitleedit
INFO:__main__:Getting metadata for https://github.com/SubtitleEdit/subtitleedit
 14%|█▍        | 40/284 [01:46<06:59,  1.72s/it]INFO:__main__:Requesting https://github.com/AlbertoSabater/subtitle-synchronization
INFO:__main__:Getting metadata for https://github.com/AlbertoSabater/subtitle-synchronization
 14%|█▍        | 41/284 [01:47<06:14,  1.54s/it]INFO:__main__:Requesting https://gist.github.com/chanux/2042676
INFO:__main__:Getting metadata for https://gist.github.com/chanux/2042676
 15%|█▍        | 42/284 [01:47<05:04,  1.26s/it]INFO:__main__:Requesting https://github.com/pettarin/forced-alignment-tools/blob/master/README.md
INFO:__main__:Getting metadata for https://github.com/pettarin/forced-alignment-tools/blob/master/README.md
 15%|█▌        | 43/284 [01:48<04:28,  1.11s/it]INFO:__main__:Requesting https://pudding.cool/2019/02/gyllenhaal/
INFO:__main__:Getting metadata for https://pudding.cool/2019/02/gyllenhaal/
 15%|█▌        | 44/284 [01:48<03:22,  1.19it/s]INFO:__main__:Requesting http://www.lel.ed.ac.uk/ihd/elalme/elalme_frames.html
INFO:__main__:Getting metadata for http://www.lel.ed.ac.uk/ihd/elalme/elalme_frames.html
 16%|█▌        | 45/284 [01:50<03:49,  1.04it/s]INFO:__main__:Requesting http://www.amc.lel.ed.ac.uk/?page_id=563
INFO:__main__:Getting metadata for http://www.amc.lel.ed.ac.uk/?page_id=563
 16%|█▌        | 46/284 [01:54<08:19,  2.10s/it]INFO:__main__:Requesting https://mashedradish.com/2017/05/16/the-bureau-of-etymological-investigation/
ERROR:__main__:Could not reach https://mashedradish.com/2017/05/16/the-bureau-of-etymological-investigation/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 209, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 17%|█▋        | 47/284 [01:54<05:58,  1.51s/it]INFO:__main__:Requesting http://www.thesmokinggun.com/documents/crime/actor-mcconaughey-nude-bongo-bust-0
INFO:__main__:Getting metadata for http://www.thesmokinggun.com/documents/crime/actor-mcconaughey-nude-bongo-bust-0
 17%|█▋        | 48/284 [01:55<04:54,  1.25s/it]INFO:__main__:Requesting https://chuckpalahniuk.net/author/frequently-asked-questions-about-chuck-palahniuk#biographical-1
INFO:__main__:Getting metadata for https://chuckpalahniuk.net/author/frequently-asked-questions-about-chuck-palahniuk#biographical-1
 17%|█▋        | 49/284 [01:56<04:26,  1.14s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Ukrainian_alphabet#Letter_names_and_pronunciation
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Ukrainian_alphabet#Letter_names_and_pronunciation
 18%|█▊        | 50/284 [01:57<04:51,  1.25s/it]INFO:__main__:Requesting https://en.wiktionary.org/wiki/ɦ
INFO:__main__:Getting metadata for https://en.wiktionary.org/wiki/%C9%A6
 18%|█▊        | 51/284 [01:58<04:17,  1.10s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Romanization_of_Ukrainian#Tables_of_romanization_systems
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Romanization_of_Ukrainian#Tables_of_romanization_systems
 18%|█▊        | 52/284 [02:00<04:31,  1.17s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Irish_name
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Irish_name
 19%|█▊        | 53/284 [02:01<04:52,  1.27s/it]INFO:__main__:Requesting https://twitter.com/BillGates/status/1086662632587907072
INFO:__main__:Getting metadata for https://twitter.com/BillGates/status/1086662632587907072
 19%|█▉        | 54/284 [02:03<05:03,  1.32s/it]INFO:__main__:Requesting https://www.theguardian.com/commentisfree/2019/jan/29/bill-gates-davos-global-poverty-infographic-neoliberal
INFO:__main__:Getting metadata for https://www.theguardian.com/commentisfree/2019/jan/29/bill-gates-davos-global-poverty-infographic-neoliberal
 19%|█▉        | 55/284 [02:03<03:57,  1.04s/it]INFO:__main__:Requesting https://voxeu.org/article/assessing-progress-poorest-new-evidence
INFO:__main__:Getting metadata for https://voxeu.org/article/assessing-progress-poorest-new-evidence
 20%|█▉        | 56/284 [02:05<04:54,  1.29s/it]INFO:__main__:Requesting https://ourworldindata.org/poverty-at-higher-poverty-lines
INFO:__main__:Getting metadata for https://ourworldindata.org/poverty-at-higher-poverty-lines
 20%|██        | 57/284 [02:05<03:44,  1.01it/s]INFO:__main__:Requesting https://ourworldindata.org/extreme-history-methods
INFO:__main__:Getting metadata for https://ourworldindata.org/extreme-history-methods
 20%|██        | 58/284 [02:05<03:00,  1.25it/s]INFO:__main__:Requesting https://akvopedia.org
INFO:__main__:Getting metadata for https://akvopedia.org/wiki/Main_Page
 21%|██        | 59/284 [02:09<06:10,  1.65s/it]INFO:__main__:Requesting https://ourworldindata.org/a-history-of-global-living-conditions-in-5-charts
INFO:__main__:Getting metadata for https://ourworldindata.org/a-history-of-global-living-conditions-in-5-charts
 21%|██        | 60/284 [02:09<04:44,  1.27s/it]INFO:__main__:Requesting https://www.cgdev.org/blog/12-things-we-can-agree-about-global-poverty
INFO:__main__:Getting metadata for https://www.cgdev.org/blog/12-things-we-can-agree-about-global-poverty
 21%|██▏       | 61/284 [02:10<03:36,  1.03it/s]INFO:__main__:Requesting http://www.developfy.com
INFO:__main__:Getting metadata for http://www.developfy.com
 22%|██▏       | 62/284 [02:11<03:53,  1.05s/it]INFO:__main__:Requesting https://mediabiasfactcheck.com/our-world-in-data/
ERROR:__main__:Could not reach https://mediabiasfactcheck.com/our-world-in-data/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 209, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 22%|██▏       | 63/284 [02:11<02:52,  1.28it/s]INFO:__main__:Requesting https://ourworldindata.org/much-better-awful-can-be-better
INFO:__main__:Getting metadata for https://ourworldindata.org/much-better-awful-can-be-better
 23%|██▎       | 64/284 [02:11<02:18,  1.59it/s]INFO:__main__:Requesting https://ourworldindata.org/homelessness-rise-england
INFO:__main__:Getting metadata for https://ourworldindata.org/homelessness-rise-england
 23%|██▎       | 65/284 [02:12<02:08,  1.71it/s]INFO:__main__:Requesting https://www.amazon.com/Influential-Mind-Reveals-Change-Others/dp/1627792651
INFO:__main__:Getting metadata for https://www.amazon.com/Influential-Mind-Reveals-Change-Others/dp/1627792651
 23%|██▎       | 66/284 [02:15<04:35,  1.26s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=NyME0Idsq9w
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=NyME0Idsq9w
 24%|██▎       | 67/284 [02:16<04:15,  1.18s/it]INFO:__main__:Requesting https://www.gapminder.org/
INFO:__main__:Getting metadata for https://www.gapminder.org
 24%|██▍       | 68/284 [02:16<03:37,  1.01s/it]INFO:__main__:Requesting https://www.gapminder.org/videos/dont-panic-end-poverty/
INFO:__main__:Getting metadata for https://www.gapminder.org/videos/dont-panic-end-poverty/
 24%|██▍       | 69/284 [02:17<03:41,  1.03s/it]INFO:__main__:Requesting https://www.gapminder.org/news/data-sources-dont-panic-end-poverty/
INFO:__main__:Getting metadata for https://www.gapminder.org/news/data-sources-dont-panic-end-poverty/
 25%|██▍       | 70/284 [02:21<06:28,  1.81s/it]INFO:__main__:Requesting https://ourworldindata.org/grapher/child-mortality
INFO:__main__:Getting metadata for https://ourworldindata.org/grapher/child-mortality
 25%|██▌       | 71/284 [02:21<04:47,  1.35s/it]INFO:__main__:Requesting https://ourworldindata.org/about/list-of-all-data-entries
INFO:__main__:Getting metadata for https://ourworldindata.org/about/list-of-all-data-entries
 25%|██▌       | 72/284 [02:22<03:39,  1.03s/it]INFO:__main__:Requesting http://www.usefulusability.com/usertesting-alternatives/
INFO:__main__:Getting metadata for http://www.usefulusability.com/usertesting-alternatives/
 26%|██▌       | 73/284 [02:22<03:16,  1.08it/s]INFO:__main__:Requesting https://www.producthunt.com/alternatives/usertesting-2
INFO:__main__:Getting metadata for https://www.producthunt.com/alternatives/usertesting-2
 26%|██▌       | 74/284 [02:23<03:22,  1.04it/s]INFO:__main__:Requesting https://medium.com/@leemunroe/how-our-product-design-team-conducts-usability-tests-every-2-weeks-afa8c60a8616
INFO:__main__:Getting metadata for https://medium.com/@leemunroe/how-our-product-design-team-conducts-usability-tests-every-2-weeks-afa8c60a8616
 26%|██▋       | 75/284 [02:24<02:56,  1.18it/s]INFO:__main__:Requesting https://fivethirtyeight.com/
INFO:__main__:Getting metadata for https://fivethirtyeight.com
 27%|██▋       | 76/284 [02:24<02:21,  1.47it/s]INFO:__main__:Requesting https://www.newyorker.com/
INFO:__main__:Getting metadata for https://www.newyorker.com
 27%|██▋       | 77/284 [02:24<01:56,  1.78it/s]INFO:__main__:Requesting https://ourworldindata.org/about/coverage#coverage
INFO:__main__:Getting metadata for https://ourworldindata.org/about/coverage#coverage
 27%|██▋       | 78/284 [02:25<01:50,  1.86it/s]INFO:__main__:Requesting https://elixir-lang.org/blog/2019/02/25/mint-a-new-http-library-for-elixir/
INFO:__main__:Getting metadata for https://elixir-lang.org/blog/2019/02/25/mint-a-new-http-library-for-elixir/
 28%|██▊       | 79/284 [02:25<01:28,  2.32it/s]INFO:__main__:Requesting https://hexdocs.pm/mojito/Mojito.html
INFO:__main__:Getting metadata for https://hexdocs.pm/mojito/Mojito.html
 28%|██▊       | 80/284 [02:26<01:34,  2.15it/s]INFO:__main__:Requesting https://github.com/appcues/mojito
INFO:__main__:Getting metadata for https://github.com/appcues/mojito
 29%|██▊       | 81/284 [02:27<02:02,  1.66it/s]INFO:__main__:Requesting https://twitter.com/whatyouhide/status/1100082898986774528
INFO:__main__:Getting metadata for https://twitter.com/whatyouhide/status/1100082898986774528
 29%|██▉       | 82/284 [02:27<02:15,  1.50it/s]INFO:__main__:Requesting https://ninenines.eu/docs/en/gun/1.3/manual/
INFO:__main__:Getting metadata for https://ninenines.eu/docs/en/gun/1.3/manual/
 29%|██▉       | 83/284 [02:28<02:16,  1.47it/s]INFO:__main__:Requesting https://github.com/elixir-maru/maru
INFO:__main__:Getting metadata for https://github.com/elixir-maru/maru
 30%|██▉       | 84/284 [02:29<02:26,  1.37it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=_JNGI1dI-e8
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=_JNGI1dI-e8
 30%|██▉       | 85/284 [02:30<02:39,  1.25it/s]INFO:__main__:Requesting https://github.com/ericmj/mint
INFO:__main__:Getting metadata for https://github.com/ericmj/mint
 30%|███       | 86/284 [02:31<02:50,  1.16it/s]INFO:__main__:Requesting http://mentalfloss.com/article/94569/clair-patterson-scientist-who-determined-age-earth-and-then-saved-it
INFO:__main__:Getting metadata for http://mentalfloss.com/article/94569/clair-patterson-scientist-who-determined-age-earth-and-then-saved-it
 31%|███       | 87/284 [02:31<02:28,  1.33it/s]INFO:__main__:Requesting https://leowid.com/brain-facts/
 31%|███       | 88/284 [02:32<01:57,  1.66it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Flashbulb_memory
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Flashbulb_memory
 31%|███▏      | 89/284 [02:33<02:54,  1.11it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Dandy%E2%80%93Walker_syndrome
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Dandy%E2%80%93Walker_syndrome
 32%|███▏      | 90/284 [02:34<02:59,  1.08it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Research_on_meditation#Research_on_unspecified_or_multiple_types_of_meditation
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Research_on_meditation#Research_on_unspecified_or_multiple_types_of_meditation
 32%|███▏      | 91/284 [02:36<04:02,  1.26s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=D9H9qTdserM
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=D9H9qTdserM
 32%|███▏      | 92/284 [02:37<03:34,  1.11s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=CAOnSbDSaOw
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=CAOnSbDSaOw
 33%|███▎      | 93/284 [02:38<03:19,  1.04s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4979579/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4979579/
 33%|███▎      | 94/284 [02:39<03:44,  1.18s/it]INFO:__main__:Requesting https://www.nature.com/articles/s41598-019-39558-8
INFO:__main__:Getting metadata for https://www.nature.com/articles/s41598-019-39558-8
 33%|███▎      | 95/284 [02:42<05:14,  1.66s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Fermi_paradox
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Fermi_paradox
 34%|███▍      | 96/284 [02:44<05:44,  1.83s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Great_Filter
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Great_Filter
 34%|███▍      | 97/284 [02:46<05:02,  1.62s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=amjuJJwI3iM
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=amjuJJwI3iM
 35%|███▍      | 98/284 [02:47<04:25,  1.43s/it]INFO:__main__:Requesting https://www.newscientist.com/article/mg21028184-300-lab-yeast-make-evolutionary-leap-to-multicellularity/
INFO:__main__:Getting metadata for https://www.newscientist.com/article/mg21028184-300-lab-yeast-make-evolutionary-leap-to-multicellularity/
 35%|███▍      | 99/284 [02:49<05:14,  1.70s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Volvox
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Volvox
 35%|███▌      | 100/284 [02:50<04:24,  1.44s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Multicellular_organism#Occurrence
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Multicellular_organism#Occurrence
 36%|███▌      | 101/284 [02:51<04:13,  1.39s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Stellar_population#Population_I_stars
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Stellar_population#Population_I_stars
 36%|███▌      | 102/284 [02:52<04:05,  1.35s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Chlamydomonadales
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Chlamydomonadales
 36%|███▋      | 103/284 [02:53<03:32,  1.17s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Caulerpa
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Caulerpa
 37%|███▋      | 104/284 [02:54<03:17,  1.10s/it]INFO:__main__:Requesting http://git.kernel.dk/cgit/linux-block/commit/?h=for-next&id=8923ebc04818fcb506829591aa8704baefd661ec
INFO:__main__:Getting metadata for http://git.kernel.dk/cgit/linux-block/commit/?h=for-next&id=8923ebc04818fcb506829591aa8704baefd661ec
 37%|███▋      | 105/284 [02:56<03:53,  1.30s/it]INFO:__main__:Requesting https://lwn.net/Articles/776703/
INFO:__main__:Getting metadata for https://lwn.net/Articles/776703/
 37%|███▋      | 106/284 [02:56<03:20,  1.13s/it]INFO:__main__:Requesting http://webdav.org/
ERROR:__main__:Could not reach http://webdav.org/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='webdav.org', port=80): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 209, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='webdav.org', port=80): Read timed out. (read timeout=6)
 38%|███▊      | 107/284 [03:03<07:44,  2.62s/it]INFO:__main__:Requesting https://github.com/mnutt/davros
INFO:__main__:Getting metadata for https://github.com/mnutt/davros
 38%|███▊      | 108/284 [03:03<06:03,  2.07s/it]INFO:__main__:Requesting https://bustbyte.no/blog/how-we-hacked-blackboard-and-changed-our-grades
INFO:__main__:Getting metadata for https://bustbyte.no/blog/how-we-hacked-blackboard-and-changed-our-grades
 38%|███▊      | 109/284 [03:04<05:02,  1.73s/it]INFO:__main__:Requesting https://www.greenbytes.de/tech/webdav/webfolder-client-list.html
INFO:__main__:Getting metadata for https://www.greenbytes.de/tech/webdav/webfolder-client-list.html
 39%|███▊      | 110/284 [03:07<05:57,  2.06s/it]INFO:__main__:Requesting https://www.greenbytes.de/tech/webdav/webdav-redirector-list.html
INFO:__main__:Getting metadata for https://www.greenbytes.de/tech/webdav/webdav-redirector-list.html
 39%|███▉      | 111/284 [03:10<06:26,  2.23s/it]INFO:__main__:Requesting https://github.com/lsst-dm/davt
INFO:__main__:Getting metadata for https://github.com/lsst-dm/davt
 39%|███▉      | 112/284 [03:11<05:10,  1.80s/it]INFO:__main__:Requesting http://sabre.io/
INFO:__main__:Getting metadata for http://sabre.io
 40%|███▉      | 113/284 [03:11<03:56,  1.38s/it]INFO:__main__:Requesting https://dokan-dev.github.io/
INFO:__main__:Getting metadata for https://dokan-dev.github.io
 40%|████      | 114/284 [03:11<03:07,  1.11s/it]INFO:__main__:Requesting https://archive.is/O0pi9
ERROR:__main__:Could not reach https://archive.is/O0pi9
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/opt/python/3.6.3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='archive.is', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 209, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/models.py", line 757, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='archive.is', port=443): Read timed out.
 40%|████      | 115/284 [03:18<08:07,  2.89s/it]INFO:__main__:Requesting https://www.taiwannews.com.tw/en/news/3644433
INFO:__main__:Getting metadata for https://www.taiwannews.com.tw/en/news/3644433
 41%|████      | 116/284 [03:20<07:10,  2.56s/it]INFO:__main__:Requesting https://www.bbc.com/news/science-environment-47311186
INFO:__main__:Getting metadata for https://www.bbc.com/news/science-environment-47311186
 41%|████      | 117/284 [03:21<05:16,  1.90s/it]INFO:__main__:Requesting https://mashable.com/article/fernandina-giant-tortoise-galapagos-extinct-discovery
INFO:__main__:Getting metadata for https://mashable.com/article/fernandina-giant-tortoise-galapagos-extinct-discovery/
 42%|████▏     | 118/284 [03:21<04:08,  1.50s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=OT0ZIq-yWEM
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=OT0ZIq-yWEM
 42%|████▏     | 119/284 [03:22<03:47,  1.38s/it]INFO:__main__:Requesting https://www.animalplanet.com/tv-shows/extinct-or-alive/
INFO:__main__:Getting metadata for https://www.animalplanet.com/tv-shows/extinct-or-alive/
 42%|████▏     | 120/284 [03:23<03:22,  1.23s/it]INFO:__main__:Requesting https://puri.sm/posts/pureboot-the-high-security-boot-process/
INFO:__main__:Getting metadata for https://puri.sm/posts/pureboot-the-high-security-boot-process/
 43%|████▎     | 121/284 [03:24<02:48,  1.03s/it]INFO:__main__:Requesting https://support.lenovo.com/us/en/downloads/ds029187
INFO:__main__:Getting metadata for https://support.lenovo.com/us/en/downloads/ds029187
 43%|████▎     | 122/284 [03:26<04:00,  1.48s/it]INFO:__main__:Requesting https://support.lenovo.com/us/en/downloads/ds029252
INFO:__main__:Getting metadata for https://support.lenovo.com/us/en/downloads/ds029252
 43%|████▎     | 123/284 [03:29<05:22,  2.00s/it]INFO:__main__:Requesting https://github.com/Cr4sh/ThinkPwn
INFO:__main__:Getting metadata for https://github.com/Cr4sh/ThinkPwn
 44%|████▎     | 124/284 [03:30<04:20,  1.63s/it]INFO:__main__:Requesting https://support.lenovo.com/us/en/solutions/len-8324
INFO:__main__:Getting metadata for https://support.lenovo.com/us/en/solutions/len-8324
 44%|████▍     | 125/284 [03:35<06:47,  2.56s/it]INFO:__main__:Requesting https://github.com/chipsec/chipsec
INFO:__main__:Getting metadata for https://github.com/chipsec/chipsec
 44%|████▍     | 126/284 [03:36<05:32,  2.11s/it]INFO:__main__:Requesting https://blog.dowhile0.org/2017/10/18/automatic-luks-volumes-unlocking-using-a-tpm2-chip/
ERROR:__main__:Could not reach https://blog.dowhile0.org/2017/10/18/automatic-luks-volumes-unlocking-using-a-tpm2-chip/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 209, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 45%|████▍     | 127/284 [03:36<03:59,  1.53s/it]INFO:__main__:Requesting https://trmm.net/Heads_33c3#Philosophy_of_Heads
INFO:__main__:Getting metadata for https://trmm.net/Heads_33c3#Philosophy_of_Heads
 45%|████▌     | 128/284 [03:37<03:37,  1.39s/it]INFO:__main__:Requesting https://github.com/TrenchBoot/documentation/blob/master/documentation/Architecture.md
INFO:__main__:Getting metadata for https://github.com/TrenchBoot/documentation/blob/master/documentation/Architecture.md
 45%|████▌     | 129/284 [03:38<03:10,  1.23s/it]INFO:__main__:Requesting http://reboot.pro/topic/7223-how-to-boot-directly-into-windows-from-kexecgrub4dos/
INFO:__main__:Getting metadata for http://reboot.pro/topic/7223-how-to-boot-directly-into-windows-from-kexecgrub4dos/
 46%|████▌     | 130/284 [03:39<02:43,  1.06s/it]INFO:__main__:Requesting https://mjg59.dreamwidth.org/50577.html
INFO:__main__:Getting metadata for https://mjg59.dreamwidth.org/50577.html
 46%|████▌     | 131/284 [03:41<03:36,  1.42s/it]INFO:__main__:Requesting https://www.percona.com/blog/2019/02/25/mysql-challenge-100k-connections/
INFO:__main__:Getting metadata for https://www.percona.com/blog/2019/02/25/mysql-challenge-100k-connections/
 46%|████▋     | 132/284 [03:42<03:02,  1.20s/it]INFO:__main__:Requesting https://github.com/diesel-rs/diesel/issues/1028#issuecomment-315748691
INFO:__main__:Getting metadata for https://github.com/diesel-rs/diesel/issues/1028#issuecomment-315748691
 47%|████▋     | 133/284 [03:43<03:09,  1.26s/it]INFO:__main__:Requesting https://www.postgresql.org/message-id/CA+CSw_tEpJ=md1zgxPkjH6CWDnTDft4gBi=+P9SnoC+Wy3pKdA@mail.gmail.com
INFO:__main__:Getting metadata for https://www.postgresql.org/message-id/CA+CSw_tEpJ=md1zgxPkjH6CWDnTDft4gBi=+P9SnoC+Wy3pKdA@mail.gmail.com
 47%|████▋     | 134/284 [03:44<02:54,  1.16s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=xNDnVOCdvQ0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=xNDnVOCdvQ0
 48%|████▊     | 135/284 [03:45<02:54,  1.17s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Amplituhedron
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Amplituhedron
 48%|████▊     | 136/284 [03:46<02:40,  1.09s/it]INFO:__main__:Requesting https://www.quantamagazine.org/physicists-discover-geometry-underlying-particle-physics-20130917/
ERROR:__main__:Could not reach https://www.quantamagazine.org/physicists-discover-geometry-underlying-particle-physics-20130917/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.quantamagazine.org', port=443): Read timed out. (read timeout=6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 209, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.quantamagazine.org', port=443): Read timed out. (read timeout=6)
 48%|████▊     | 137/284 [03:52<06:21,  2.60s/it]INFO:__main__:Requesting https://djhworld.github.io/post/2019/02/24/reed-solomon-codes-are-cool/
INFO:__main__:Getting metadata for https://djhworld.github.io/post/2019/02/24/reed-solomon-codes-are-cool/
 49%|████▊     | 138/284 [03:53<04:40,  1.92s/it]INFO:__main__:Requesting https://www.nayuki.io/page/reed-solomon-error-correcting-code-decoder
INFO:__main__:Getting metadata for https://www.nayuki.io/page/reed-solomon-error-correcting-code-decoder
 49%|████▉     | 139/284 [03:53<03:51,  1.60s/it]INFO:__main__:Requesting https://en.m.wikipedia.org/wiki/Reed–Solomon_error_correction#Reed_&_Solomon's_original_view:_The_codeword_as_a_sequence_of_values
INFO:__main__:Getting metadata for https://en.m.wikipedia.org/wiki/Reed%E2%80%93Solomon_error_correction#Reed_&_Solomon's_original_view:_The_codeword_as_a_sequence_of_values
 49%|████▉     | 140/284 [03:57<05:30,  2.30s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=x1v2tX4_dkQ
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=x1v2tX4_dkQ
 50%|████▉     | 141/284 [03:58<04:31,  1.90s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Binary_Golay_code
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Binary_Golay_code
 50%|█████     | 142/284 [03:59<03:54,  1.65s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Sporadic_group
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Sporadic_group
 50%|█████     | 143/284 [04:01<03:43,  1.58s/it]INFO:__main__:Requesting https://www.amazon.com/Fundamentals-Error-Correcting-Codes-Cary-Huffman/dp/0521131707
INFO:__main__:Getting metadata for https://www.amazon.com/Fundamentals-Error-Correcting-Codes-Cary-Huffman/dp/0521131707
 51%|█████     | 144/284 [04:04<04:42,  2.02s/it]INFO:__main__:Requesting https://en.wikiversity.org/wiki/Reed%E2%80%93Solomon_codes_for_coders
INFO:__main__:Getting metadata for https://en.wikiversity.org/wiki/Reed%E2%80%93Solomon_codes_for_coders
 51%|█████     | 145/284 [04:06<04:41,  2.02s/it]INFO:__main__:Requesting https://www.akalin.com/intro-erasure-codes
INFO:__main__:Getting metadata for https://www.akalin.com/intro-erasure-codes
 51%|█████▏    | 146/284 [04:08<04:38,  2.02s/it]INFO:__main__:Requesting https://manuelfi.com/blog/hamming-code-simulator/
INFO:__main__:Getting metadata for https://manuelfi.com/blog/hamming-code-simulator/
 52%|█████▏    | 147/284 [04:08<03:28,  1.52s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Fountain_code
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Fountain_code
 52%|█████▏    | 148/284 [04:09<02:59,  1.32s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Mojette_Transform
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Mojette_Transform
 52%|█████▏    | 149/284 [04:10<02:43,  1.21s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=fBRMaEAFLE0
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=fBRMaEAFLE0
 53%|█████▎    | 150/284 [04:11<02:25,  1.09s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/8b/10b_encoding
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/8b/10b_encoding
 53%|█████▎    | 151/284 [04:12<02:24,  1.09s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/64b/66b_encoding
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/64b/66b_encoding
 54%|█████▎    | 152/284 [04:13<02:16,  1.03s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Hamming_code
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Hamming_code
 54%|█████▍    | 153/284 [04:14<02:32,  1.16s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Adaptive_Multi-Rate_audio_codec
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Adaptive_Multi-Rate_audio_codec
 54%|█████▍    | 154/284 [04:16<02:32,  1.17s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Adaptive_Multi-Rate_Wideband
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Adaptive_Multi-Rate_Wideband
 55%|█████▍    | 155/284 [04:17<02:28,  1.16s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Raptor_code
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Raptor_code
 55%|█████▍    | 156/284 [04:17<02:11,  1.03s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Turbo_code
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Turbo_code
 55%|█████▌    | 157/284 [04:19<02:16,  1.07s/it]INFO:__main__:Requesting https://blogs.dropbox.com/tech/2016/07/pocket-watch/
INFO:__main__:Getting metadata for https://blogs.dropbox.com/tech/2016/07/pocket-watch/
 56%|█████▌    | 158/284 [04:20<02:34,  1.22s/it]INFO:__main__:Requesting https://perspectives.mvdirona.com/2009/06/erasure-coding-and-cold-storage/
INFO:__main__:Getting metadata for https://perspectives.mvdirona.com/2009/06/erasure-coding-and-cold-storage/
 56%|█████▌    | 159/284 [04:23<03:21,  1.62s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Low-density_parity-check_code
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Low-density_parity-check_code
 56%|█████▋    | 160/284 [04:24<03:06,  1.51s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Polar_code_(coding_theory)
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Polar_code_(coding_theory)
 57%|█████▋    | 161/284 [04:25<02:37,  1.28s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Error_correction_code
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Error_correction_code
 57%|█████▋    | 162/284 [04:26<02:31,  1.24s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Clock_recovery
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Clock_recovery
 57%|█████▋    | 163/284 [04:27<02:11,  1.09s/it]INFO:__main__:Requesting https://fenrirproject.org/Luker/libRaptorQ/wikis/home
INFO:__main__:Getting metadata for https://fenrirproject.org/Luker/libRaptorQ/wikis/home
 58%|█████▊    | 164/284 [04:28<02:33,  1.28s/it]INFO:__main__:Requesting https://github.com/tahoe-lafs/zfec
INFO:__main__:Getting metadata for https://github.com/tahoe-lafs/zfec
 58%|█████▊    | 165/284 [04:29<02:24,  1.21s/it]INFO:__main__:Requesting https://github.com/openstack/liberasurecode
INFO:__main__:Getting metadata for https://github.com/openstack/liberasurecode
 58%|█████▊    | 166/284 [04:30<02:09,  1.10s/it]INFO:__main__:Requesting https://github.com/catid/cm256
INFO:__main__:Getting metadata for https://github.com/catid/cm256
 59%|█████▉    | 167/284 [04:31<02:03,  1.06s/it]INFO:__main__:Requesting http://openrq-team.github.io/openrq/
INFO:__main__:Getting metadata for http://openrq-team.github.io/openrq/
 59%|█████▉    | 168/284 [04:31<01:33,  1.24it/s]INFO:__main__:Requesting http://openfec.org/
INFO:__main__:Getting metadata for http://openfec.org
 60%|█████▉    | 169/284 [04:33<01:52,  1.02it/s]INFO:__main__:Requesting https://github.com/Spriteware/lt-codes-python
INFO:__main__:Getting metadata for https://github.com/Spriteware/lt-codes-python
 60%|█████▉    | 170/284 [04:34<01:49,  1.04it/s]INFO:__main__:Requesting https://www.futurice.com/blog/improving-documentation-of-open-source-software/
INFO:__main__:Getting metadata for https://www.futurice.com/blog/improving-documentation-of-open-source-software/
 60%|██████    | 171/284 [04:34<01:34,  1.20it/s]INFO:__main__:Requesting https://www.writethedocs.org
INFO:__main__:Getting metadata for https://www.writethedocs.org
 61%|██████    | 172/284 [04:35<01:44,  1.07it/s]INFO:__main__:Requesting https://arxiv.org/abs/1902.06855
INFO:__main__:Getting metadata for https://arxiv.org/abs/1902.06855
 61%|██████    | 173/284 [04:36<01:43,  1.07it/s]INFO:__main__:Requesting https://arxiv.org/abs/1811.06992
INFO:__main__:Getting metadata for https://arxiv.org/abs/1811.06992
 61%|██████▏   | 174/284 [04:37<01:44,  1.05it/s]INFO:__main__:Requesting https://www.the-tls.co.uk/articles/public/charles-catherine-dickens-asylum/
INFO:__main__:Getting metadata for https://www.the-tls.co.uk/articles/public/charles-catherine-dickens-asylum/
 62%|██████▏   | 175/284 [04:42<03:40,  2.02s/it]INFO:__main__:Requesting https://www.theatlantic.com/technology/archive/2019/02/when-kids-realize-their-whole-life-already-online/582916/
INFO:__main__:Getting metadata for https://www.theatlantic.com/technology/archive/2019/02/when-kids-realize-their-whole-life-already-online/582916/
 62%|██████▏   | 176/284 [04:42<02:39,  1.48s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Murder_of_James_Bulger
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Murder_of_James_Bulger
 62%|██████▏   | 177/284 [04:44<02:49,  1.59s/it]INFO:__main__:Requesting https://www.google.com/amp/s/amp.theguardian.com/world/2019/jan/25/david-matheson-former-gay-conversion-therapy-advocate-comes-out
INFO:__main__:Getting metadata for https://www.theguardian.com/world/2019/jan/25/david-matheson-former-gay-conversion-therapy-advocate-comes-out
 63%|██████▎   | 178/284 [04:45<02:19,  1.32s/it]INFO:__main__:Requesting https://www.wsj.com/articles/sec-asks-manhattan-federal-court-to-hold-elon-musk-in-contempt-11551137500
INFO:__main__:Getting metadata for https://www.wsj.com/articles/sec-asks-manhattan-federal-court-to-hold-elon-musk-in-contempt-11551137500
 63%|██████▎   | 179/284 [04:45<02:02,  1.17s/it]INFO:__main__:Requesting https://www.cnbc.com/2019/02/20/tesla-replaces-general-counsel-dane-butswinkas.html
INFO:__main__:Getting metadata for https://www.cnbc.com/2019/02/20/tesla-replaces-general-counsel-dane-butswinkas.html
 63%|██████▎   | 180/284 [04:46<01:39,  1.05it/s]INFO:__main__:Requesting https://www.thestreet.com/investing/stocks/how-elon-musk-controls-tesla-with-only-a-minority-stake-14564491
INFO:__main__:Requesting https://twitter.com/_jameshatfield_/status/1100177298723094528
INFO:__main__:Getting metadata for https://twitter.com/_jameshatfield_/status/1100177298723094528
 64%|██████▍   | 182/284 [04:47<01:23,  1.22it/s]INFO:__main__:Requesting https://www.documentcloud.org/documents/5750664-Show-Cause.html
INFO:__main__:Getting metadata for https://www.documentcloud.org/documents/5750664-Show-Cause.html
 64%|██████▍   | 183/284 [04:47<01:07,  1.49it/s]INFO:__main__:Requesting https://www.google.com/search?rlz=1C1CHBF_enUS791US791&biw=1920&bih=969&ei=Ioh0XPmSD4CT0PEPwZCHuAc&q=site%3Awww.tesla.com+twitter+%2B%22%22%22elonmusk%22%22%22&oq=site%3Awww.tesla.com+twitter+%2B%22%22%22elonmusk%22%22%22&gs_l=psy-ab.3...14343.19919..20515...0.0..0.79.495.7......0....1..gws-wiz.......0i71.CaBEIVRzxiI
INFO:__main__:Getting metadata for https://www.google.com/search?rlz=1C1CHBF_enUS791US791&biw=1920&bih=969&ei=Ioh0XPmSD4CT0PEPwZCHuAc&q=site%3Awww.tesla.com+twitter+%2B%22%22%22elonmusk%22%22%22&oq=site%3Awww.tesla.com+twitter+%2B%22%22%22elonmusk%22%22%22&gs_l=psy-ab.3...14343.19919..20515...0.0..0.79.495.7......0....1..gws-wiz.......0i71.CaBEIVRzxiI
 65%|██████▍   | 184/284 [04:50<02:05,  1.25s/it]INFO:__main__:Requesting https://www.sec.gov/Archives/edgar/data/1318605/000119312513427630/d622890d8k.htm
INFO:__main__:Getting metadata for https://www.sec.gov/Archives/edgar/data/1318605/000119312513427630/d622890d8k.htm
 65%|██████▌   | 185/284 [04:51<02:14,  1.36s/it]INFO:__main__:Requesting https://twitter.com/elonmusk/status/1098009983931707393
INFO:__main__:Getting metadata for https://twitter.com/elonmusk/status/1098009983931707393
 65%|██████▌   | 186/284 [04:54<02:36,  1.60s/it]INFO:__main__:Requesting http://ir.tesla.com/static-files/0b913415-467d-4c0d-be4c-9225c2cb0ae0
INFO:__main__:Getting metadata for http://ir.tesla.com/static-files/0b913415-467d-4c0d-be4c-9225c2cb0ae0
 66%|██████▌   | 187/284 [05:11<10:30,  6.50s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=zpWYQ1YtgnI
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=zpWYQ1YtgnI
 66%|██████▌   | 188/284 [05:13<07:47,  4.87s/it]INFO:__main__:Requesting https://www.cnbc.com/2019/02/25/tesla-shares-fall-on-report-sec-asks-judge-to-hold-elon-musk-in-contempt-for-violating-deal.html
INFO:__main__:Getting metadata for https://www.cnbc.com/2019/02/25/tesla-shares-fall-on-report-sec-asks-judge-to-hold-elon-musk-in-contempt-for-violating-deal.html
 67%|██████▋   | 189/284 [05:13<05:31,  3.49s/it]INFO:__main__:Requesting https://www.theverge.com/2018/9/29/17918252/elon-musk-tesla-sec-securities-fraud-lawsuit-settlement-fine-penalty
INFO:__main__:Getting metadata for https://www.theverge.com/2018/9/29/17918252/elon-musk-tesla-sec-securities-fraud-lawsuit-settlement-fine-penalty
 67%|██████▋   | 190/284 [05:13<04:03,  2.59s/it]INFO:__main__:Requesting https://twitter.com/elonmusk/status/1100215984713957376
INFO:__main__:Getting metadata for https://twitter.com/elonmusk/status/1100215984713957376
 67%|██████▋   | 191/284 [05:14<03:16,  2.12s/it]INFO:__main__:Requesting https://www.npr.org/sections/thesalt/2015/03/26/394339284/how-snobbery-helped-take-the-spice-out-of-european-cooking
INFO:__main__:Getting metadata for https://www.npr.org/sections/thesalt/2015/03/26/394339284/how-snobbery-helped-take-the-spice-out-of-european-cooking
 68%|██████▊   | 192/284 [05:15<02:30,  1.64s/it]INFO:__main__:Requesting https://www.snpedia.com/index.php/Rs72921001
INFO:__main__:Getting metadata for https://www.snpedia.com/index.php/Rs72921001
 68%|██████▊   | 193/284 [05:18<03:16,  2.16s/it]INFO:__main__:Requesting http://antirez.com/news/127
INFO:__main__:Getting metadata for http://antirez.com/news/127
 68%|██████▊   | 194/284 [05:19<02:46,  1.85s/it]INFO:__main__:Requesting https://www.minnpost.com/business/2016/08/rise-and-fall-gopher-protocol/
INFO:__main__:Getting metadata for https://www.minnpost.com/business/2016/08/rise-and-fall-gopher-protocol/
 69%|██████▊   | 195/284 [05:21<02:33,  1.72s/it]INFO:__main__:Requesting https://techcrunch.com/2019/02/25/ubiquitilink-advance-means-every-phone-is-now-a-satellite-phone/
ERROR:__main__:Could not reach https://techcrunch.com/2019/02/25/ubiquitilink-advance-means-every-phone-is-now-a-satellite-phone/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 209, in metafy_url
    response = requests.get(url, timeout=6, headers={'User-Agent': 'Mozilla/5.0'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
 69%|██████▉   | 196/284 [05:21<01:49,  1.25s/it]INFO:__main__:Requesting http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4807:7mky7n.2.1
INFO:__main__:Getting metadata for http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4807:7mky7n.2.1
 69%|██████▉   | 197/284 [05:22<01:37,  1.12s/it]INFO:__main__:Requesting https://xkcd.com/554/
INFO:__main__:Getting metadata for https://xkcd.com/554/
 70%|██████▉   | 198/284 [05:22<01:17,  1.11it/s]INFO:__main__:Requesting https://www.cbc.ca/radio/thecurrent/the-current-for-february-25-2019-1.5032165/starbucks-music-is-driving-employees-nuts-a-writer-says-it-s-a-workers-rights-issue-1.5028163
INFO:__main__:Getting metadata for https://www.cbc.ca/radio/thecurrent/the-current-for-february-25-2019-1.5032165/starbucks-music-is-driving-employees-nuts-a-writer-says-it-s-a-workers-rights-issue-1.5028163
 70%|███████   | 199/284 [05:23<01:04,  1.32it/s]INFO:__main__:Requesting https://duckduckgo.com/?q=Future+unevenly+distributed&t=fpas&ia=web
INFO:__main__:Getting metadata for https://duckduckgo.com/?q=Future+unevenly+distributed&t=fpas&ia=web
 70%|███████   | 200/284 [05:23<01:05,  1.27it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Fifteen_Million_Merits
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Fifteen_Million_Merits
 71%|███████   | 201/284 [05:24<01:13,  1.14it/s]INFO:__main__:Requesting https://www.theatlantic.com/entertainment/archive/2015/02/starbuckss-failed-music-revolution/385937/
INFO:__main__:Getting metadata for https://www.theatlantic.com/entertainment/archive/2015/02/starbuckss-failed-music-revolution/385937/
 71%|███████   | 202/284 [05:25<01:03,  1.28it/s]INFO:__main__:Requesting https://archive.org/details/attentionkmartshoppers
INFO:__main__:Getting metadata for https://archive.org/details/attentionkmartshoppers
 71%|███████▏  | 203/284 [05:32<03:31,  2.61s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=N8-0wQmPeMg
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=N8-0wQmPeMg
 72%|███████▏  | 204/284 [05:33<02:47,  2.09s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=5uV1zrZFzZo
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=5uV1zrZFzZo
 72%|███████▏  | 205/284 [05:34<02:18,  1.75s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=PEDaRQO5Utk
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=PEDaRQO5Utk
 73%|███████▎  | 206/284 [05:35<01:55,  1.48s/it]INFO:__main__:Requesting https://youtu.be/JlBnLlKPPGA?t=11
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=JlBnLlKPPGA&feature=youtu.be&t=11
 73%|███████▎  | 207/284 [05:36<01:41,  1.31s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=kB4fm_kO1us
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=kB4fm_kO1us
 73%|███████▎  | 208/284 [05:36<01:30,  1.19s/it]INFO:__main__:Requesting https://us.moodmedia.com/custom-music-business/
INFO:__main__:Getting metadata for https://us.moodmedia.com/custom-music-business/
 74%|███████▎  | 209/284 [05:38<01:44,  1.40s/it]INFO:__main__:Requesting https://journals.lww.com/thehearingjournal/FullText/2016/08000/Embracing_the_Enigma_of_Auditory_Processing.12.aspx
INFO:__main__:Getting metadata for https://journals.lww.com/thehearingjournal/FullText/2016/08000/Embracing_the_Enigma_of_Auditory_Processing.12.aspx
 74%|███████▍  | 210/284 [05:39<01:38,  1.33s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/pubmed/29056453
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/pubmed/29056453
 74%|███████▍  | 211/284 [05:43<02:26,  2.00s/it]INFO:__main__:Requesting https://www.theguardian.com/music/2014/feb/07/skinny-puppy-payment-guantanamo
INFO:__main__:Getting metadata for https://www.theguardian.com/music/2014/feb/07/skinny-puppy-payment-guantanamo
 75%|███████▍  | 212/284 [05:43<01:50,  1.53s/it]INFO:__main__:Requesting https://coffitivity.com
INFO:__main__:Getting metadata for https://coffitivity.com
 75%|███████▌  | 213/284 [05:44<01:32,  1.30s/it]INFO:__main__:Requesting https://rainymood.com
INFO:__main__:Getting metadata for https://rainymood.com
 75%|███████▌  | 214/284 [05:45<01:13,  1.05s/it]INFO:__main__:Requesting https://www.fastcompany.com/3067250/meet-the-music-nerds-behind-the-tunes-you-hear-at-starbucks
INFO:__main__:Getting metadata for https://www.fastcompany.com/3067250/meet-the-music-nerds-behind-the-tunes-you-hear-at-starbucks
 76%|███████▌  | 215/284 [05:45<00:59,  1.15it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=zucBfXpCA6s
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=zucBfXpCA6s
 76%|███████▌  | 216/284 [05:46<01:03,  1.07it/s]INFO:__main__:Requesting https://i.imgur.com/Pzd3lIk.png
INFO:__main__:Getting metadata for https://i.imgur.com/Pzd3lIk.png
 76%|███████▋  | 217/284 [05:54<03:12,  2.87s/it]INFO:__main__:Requesting https://i.imgur.com/qXkEUZl.jpg
INFO:__main__:Getting metadata for https://i.imgur.com/qXkEUZl.jpg
 77%|███████▋  | 218/284 [06:01<04:34,  4.16s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=QnkrL42R7gk
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=QnkrL42R7gk
 77%|███████▋  | 219/284 [06:02<03:24,  3.15s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=iJyYrrDKYZE
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=iJyYrrDKYZE
 77%|███████▋  | 220/284 [06:03<02:41,  2.52s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=a4QSu1ZHunw
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=a4QSu1ZHunw
 78%|███████▊  | 221/284 [06:04<02:08,  2.04s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=igGcWRYhr1Y&index=14&list=RD36YlB_6dUic
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=igGcWRYhr1Y&index=14&list=RD36YlB_6dUic
 78%|███████▊  | 222/284 [06:05<01:49,  1.77s/it]INFO:__main__:Requesting https://club.myce.com/t/starbucks-playnetwork-playdisc-aud-format/63734/67
INFO:__main__:Getting metadata for https://club.myce.com/t/starbucks-playnetwork-playdisc-aud-format/63734/67
 79%|███████▊  | 223/284 [06:06<01:31,  1.49s/it]INFO:__main__:Requesting https://support.spotify.com/is/using_spotify/the_basics/use-spotify-in-my-bar-restaurant-store-school-etc/
INFO:__main__:Getting metadata for https://support.spotify.com/is/using_spotify/the_basics/use-spotify-in-my-bar-restaurant-store-school-etc/
 79%|███████▉  | 224/284 [06:06<01:05,  1.10s/it]INFO:__main__:Requesting https://blog.jonlu.ca/posts/experiments-and-growth-hacking?ref=hackernews
INFO:__main__:Getting metadata for https://blog.jonlu.ca/posts/experiments-and-growth-hacking?ref=hackernews
 79%|███████▉  | 225/284 [06:06<00:57,  1.02it/s]INFO:__main__:Requesting https://www.guardsquare.com/en/blog/iOS-SSL-certificate-pinning-bypassing
INFO:__main__:Getting metadata for https://www.guardsquare.com/en/blog/iOS-SSL-certificate-pinning-bypassing
 80%|███████▉  | 226/284 [06:12<02:10,  2.26s/it]INFO:__main__:Requesting https://github.com/iSECPartners/ios-ssl-kill-switch
INFO:__main__:Getting metadata for https://github.com/iSECPartners/ios-ssl-kill-switch
 80%|███████▉  | 227/284 [06:12<01:43,  1.82s/it]INFO:__main__:Requesting https://discordapp.com/api/experiments
INFO:__main__:Getting metadata for https://discordapp.com/api/experiments
 80%|████████  | 228/284 [06:13<01:21,  1.46s/it]INFO:__main__:Requesting https://blog.jonlu.ca/posts/ryan-air
INFO:__main__:Getting metadata for https://blog.jonlu.ca/posts/ryan-air
 81%|████████  | 229/284 [06:14<01:06,  1.21s/it]INFO:__main__:Requesting https://blog.jonlu.ca/posts/uber-stats
INFO:__main__:Getting metadata for https://blog.jonlu.ca/posts/uber-stats
 81%|████████  | 230/284 [06:14<00:56,  1.05s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/United_States_v._Swartz
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/United_States_v._Swartz
 81%|████████▏ | 231/284 [06:16<01:00,  1.14s/it]INFO:__main__:Requesting https://www.nytimes.com/2019/02/08/well/live/does-sunlight-through-glass-provide-vitamin-d.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2019/02/08/well/live/does-sunlight-through-glass-provide-vitamin-d.html
 82%|████████▏ | 232/284 [06:16<00:45,  1.15it/s]INFO:__main__:Requesting https://www.sciencedirect.com/science/article/pii/0273230092900358
INFO:__main__:Getting metadata for https://www.sciencedirect.com/science/article/pii/0273230092900358
 82%|████████▏ | 233/284 [06:17<00:43,  1.18it/s]INFO:__main__:Requesting https://valtsus.blogspot.com/2017/05/the-therapeutic-effects-of-red-and-near.html
INFO:__main__:Getting metadata for https://valtsus.blogspot.com/2017/05/the-therapeutic-effects-of-red-and-near.html
 82%|████████▏ | 234/284 [06:18<00:47,  1.06it/s]INFO:__main__:Requesting https://www.quora.com/Can-infrared-light-pass-through-glass
INFO:__main__:Getting metadata for https://www.quora.com/Can-infrared-light-pass-through-glass
 83%|████████▎ | 235/284 [06:21<01:10,  1.44s/it]INFO:__main__:Requesting https://www.sciencedirect.com/science/article/pii/S0022202X15368974
INFO:__main__:Getting metadata for https://www.sciencedirect.com/science/article/pii/S0022202X15368974
 83%|████████▎ | 236/284 [06:21<00:55,  1.16s/it]INFO:__main__:Requesting https://www.outsideonline.com/2380751/sunscreen-sun-exposure-skin-cancer-science
INFO:__main__:Getting metadata for https://www.outsideonline.com/2380751/sunscreen-sun-exposure-skin-cancer-science
 83%|████████▎ | 237/284 [06:21<00:41,  1.14it/s]INFO:__main__:Requesting https://www.health.govt.nz/your-health/healthy-living/food-activity-and-sleep/healthy-eating/vitamin-d
INFO:__main__:Getting metadata for https://www.health.govt.nz/your-health/healthy-living/food-activity-and-sleep/healthy-eating/vitamin-d
 84%|████████▍ | 238/284 [06:24<01:00,  1.32s/it]INFO:__main__:Requesting https://slatestarcodex.com/2018/07/10/melatonin-much-more-than-you-wanted-to-know/
INFO:__main__:Getting metadata for https://slatestarcodex.com/2018/07/10/melatonin-much-more-than-you-wanted-to-know/
 84%|████████▍ | 239/284 [06:24<00:50,  1.12s/it]INFO:__main__:Requesting https://www.quora.com/Why-does-glass-block-UV
INFO:__main__:Getting metadata for https://www.quora.com/Why-does-glass-block-UV
 85%|████████▍ | 240/284 [06:27<01:14,  1.68s/it]INFO:__main__:Requesting https://www.sindark.com/2011/02/22/feynman-and-the-trinity-test/
INFO:__main__:Getting metadata for https://www.sindark.com/2011/02/22/feynman-and-the-trinity-test/
 85%|████████▍ | 241/284 [06:29<01:07,  1.58s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Demon_core
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Demon_core
 85%|████████▌ | 242/284 [06:30<01:00,  1.45s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=vwsHRrDYu5o
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=vwsHRrDYu5o
 86%|████████▌ | 243/284 [06:31<00:53,  1.30s/it]INFO:__main__:Requesting https://www.huffingtonpost.ca/2012/06/06/bill-mcelligott-sun-damage_n_1573546.html
INFO:__main__:Getting metadata for https://www.huffingtonpost.ca/2012/06/06/bill-mcelligott-sun-damage_n_1573546.html
 86%|████████▌ | 244/284 [06:32<00:45,  1.15s/it]INFO:__main__:Requesting http://archive.is/aVhiM
INFO:__main__:Getting metadata for http://archive.is/aVhiM
ERROR:__main__:Could not get metadata for http://archive.is/aVhiM
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1c6c21b9e8>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='archive.is', port=80): Max retries exceeded with url: /aVhiM (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1c6c21b9e8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='archive.is', port=80): Max retries exceeded with url: /aVhiM (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1c6c21b9e8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 86%|████████▋ | 245/284 [08:40<25:39, 39.47s/it]INFO:__main__:Requesting https://www.nejm.org/doi/full/10.1056/NEJMicm1104059
INFO:__main__:Getting metadata for https://www.nejm.org/doi/full/10.1056/NEJMicm1104059
 87%|████████▋ | 246/284 [08:42<17:47, 28.09s/it]INFO:__main__:Requesting http://www.company7.com/nikon/lens/0105f4.5uv.html
INFO:__main__:Getting metadata for http://www.company7.com/nikon/lens/0105f4.5uv.html
 87%|████████▋ | 247/284 [08:43<12:22, 20.07s/it]INFO:__main__:Requesting https://www.skincancer.org/prevention/uva-and-uvb
INFO:__main__:Getting metadata for https://www.skincancer.org/prevention/uva-and-uvb
 87%|████████▋ | 248/284 [08:44<08:36, 14.35s/it]INFO:__main__:Requesting https://www.youtube.com/watch?v=V9K6gjR07Po
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=V9K6gjR07Po
 88%|████████▊ | 249/284 [08:45<06:01, 10.33s/it]INFO:__main__:Requesting https://www.npr.org/sections/health-shots/2018/11/10/666545527/vitamin-d-and-fish-oil-supplements-disappoint-in-long-awaited-study-results
INFO:__main__:Getting metadata for https://www.npr.org/sections/health-shots/2018/11/10/666545527/vitamin-d-and-fish-oil-supplements-disappoint-in-long-awaited-study-results
 88%|████████▊ | 250/284 [08:46<04:09,  7.33s/it]INFO:__main__:Requesting https://www.theguardian.com/science/2018/mar/09/is-vitamin-d-really-a-cure-all-and-how-should-we-get-our-fix
INFO:__main__:Getting metadata for https://www.theguardian.com/science/2018/mar/09/is-vitamin-d-really-a-cure-all-and-how-should-we-get-our-fix
 88%|████████▊ | 251/284 [08:46<02:54,  5.27s/it]INFO:__main__:Requesting https://www.nytimes.com/2018/08/18/business/vitamin-d-michael-holick.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2018/08/18/business/vitamin-d-michael-holick.html
 89%|████████▊ | 252/284 [08:46<02:00,  3.77s/it]INFO:__main__:Requesting https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/expert-answers/vitamin-d-toxicity/faq-20058108
INFO:__main__:Getting metadata for https://www.mayoclinic.org/healthy-lifestyle/nutrition-and-healthy-eating/expert-answers/vitamin-d-toxicity/faq-20058108
 89%|████████▉ | 253/284 [08:47<01:23,  2.70s/it]INFO:__main__:Requesting http://www.usp.org/verification-services/verified-mark
INFO:__main__:Getting metadata for http://www.usp.org/verification-services/verified-mark
 89%|████████▉ | 254/284 [08:47<01:03,  2.12s/it]INFO:__main__:Requesting https://www.consumerreports.org/vitamins-supplements/what-usp-verified-and-other-supplement-seals-mean/
INFO:__main__:Getting metadata for https://www.consumerreports.org/vitamins-supplements/what-usp-verified-and-other-supplement-seals-mean/
 90%|████████▉ | 255/284 [08:48<00:46,  1.60s/it]INFO:__main__:Requesting http://cphpost.dk/news/danish-health-authority-warns-of-toxic-vitamin-d-product.html
INFO:__main__:Getting metadata for http://cphpost.dk/news/danish-health-authority-warns-of-toxic-vitamin-d-product.html
 90%|█████████ | 256/284 [08:52<01:05,  2.33s/it]INFO:__main__:Requesting https://labdoor.com/
INFO:__main__:Getting metadata for https://labdoor.com
 90%|█████████ | 257/284 [08:52<00:47,  1.75s/it]INFO:__main__:Requesting https://drhyman.com/blog/2010/08/24/vitamin-d-why-you-are-probably-not-getting-enough/
INFO:__main__:Getting metadata for https://drhyman.com/blog/2010/08/24/vitamin-d-why-you-are-probably-not-getting-enough/
 91%|█████████ | 258/284 [08:55<00:53,  2.08s/it]INFO:__main__:Requesting https://www.ncbi.nlm.nih.gov/m/pubmed/28768407/
INFO:__main__:Getting metadata for https://www.ncbi.nlm.nih.gov/m/pubmed/28768407/
 91%|█████████ | 259/284 [08:58<01:00,  2.43s/it]INFO:__main__:Requesting https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-d/
INFO:__main__:Getting metadata for https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-d/
 92%|█████████▏| 260/284 [08:58<00:43,  1.80s/it]INFO:__main__:Requesting https://www.health.harvard.edu/staying-healthy/should-you-get-your-nutrients-from-food-or-from-supplements
INFO:__main__:Getting metadata for https://www.health.harvard.edu/staying-healthy/should-you-get-your-nutrients-from-food-or-from-supplements
 92%|█████████▏| 261/284 [08:59<00:32,  1.41s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/The_dose_makes_the_poison
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/The_dose_makes_the_poison
 92%|█████████▏| 262/284 [09:00<00:26,  1.22s/it]INFO:__main__:Requesting https://blog.oup.com/2015/01/kin-group-selection-controversy/
INFO:__main__:Getting metadata for https://blog.oup.com/2015/01/kin-group-selection-controversy/
 93%|█████████▎| 263/284 [09:01<00:27,  1.30s/it]INFO:__main__:Requesting http://www.bbc.co.uk/earth/story/20150420-why-do-women-have-periods
INFO:__main__:Getting metadata for http://www.bbc.co.uk/earth/story/20150420-why-do-women-have-periods
 93%|█████████▎| 264/284 [09:03<00:29,  1.46s/it]INFO:__main__:Requesting https://www.bbc.com/news/science-environment-42939192
INFO:__main__:Getting metadata for https://www.bbc.com/news/science-environment-42939192
 93%|█████████▎| 265/284 [09:04<00:23,  1.23s/it]INFO:__main__:Requesting https://jamanetwork.com/journals/jamaophthalmology/fullarticle/2588252
INFO:__main__:Getting metadata for https://jamanetwork.com/journals/jamaophthalmology/fullarticle/2588252
ERROR:__main__:Could not get metadata for https://jamanetwork.com/journals/jamaophthalmology/fullarticle/2588252
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.3/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 34, in __init__
    res = requests.get(url, timeout=timeout, headers=headers)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_scripts/crawler/crawler.py", line 93, in _get_site_title_and_description
    title, description, _ = web_preview(url, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 190, in web_preview
    og = OpenGraph(url, ['og:title', 'og:description', 'og:image'], timeout=timeout, headers=headers, content=content)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 165, in __init__
    super(OpenGraph, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 131, in __init__
    super(SocialPreviewBase, self).__init__(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpreview/previews.py", line 36, in __init__
    raise URLUnreachable("The URL does not exist.")
webpreview.excepts.URLUnreachable: The URL does not exist.
 94%|█████████▎| 266/284 [09:06<00:24,  1.38s/it]INFO:__main__:Requesting https://www.nytimes.com/2018/02/16/well/live/do-i-get-enough-vitamin-d-in-the-winter.html
INFO:__main__:Getting metadata for https://www.nytimes.com/2018/02/16/well/live/do-i-get-enough-vitamin-d-in-the-winter.html
 94%|█████████▍| 267/284 [09:06<00:21,  1.25s/it]INFO:__main__:Requesting https://makezine.com/projects/build-hack-and-deploy-detectors-to-measure-solar-uv-radiation/
INFO:__main__:Getting metadata for https://makezine.com/projects/build-hack-and-deploy-detectors-to-measure-solar-uv-radiation/
 94%|█████████▍| 268/284 [09:07<00:15,  1.04it/s]INFO:__main__:Requesting https://www.solarmeter.com/model65.html
 95%|█████████▍| 269/284 [09:07<00:11,  1.25it/s]INFO:__main__:Requesting https://www.sperti.com/product/sperti-vitamin-d-light-box
INFO:__main__:Getting metadata for https://www.sperti.com/product/sperti-vitamin-d-light-box
 95%|█████████▌| 270/284 [09:08<00:10,  1.29it/s]INFO:__main__:Requesting https://www.fdalabelcompliance.com/letters/ucm284022
INFO:__main__:Getting metadata for https://www.fdalabelcompliance.com/letters/ucm284022
 95%|█████████▌| 271/284 [09:09<00:12,  1.08it/s]INFO:__main__:Requesting https://www.circadianoptics.com/
INFO:__main__:Getting metadata for https://www.circadianoptics.com
 96%|█████████▌| 272/284 [09:10<00:10,  1.17it/s]INFO:__main__:Requesting https://www.nytimes.com/column/ask-well
INFO:__main__:Getting metadata for https://www.nytimes.com/column/ask-well
 96%|█████████▌| 273/284 [09:12<00:12,  1.15s/it]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines
 96%|█████████▋| 274/284 [09:12<00:10,  1.04s/it]INFO:__main__:Requesting https://www.citylab.com/equity/2019/02/berlin-germany-housing-rent-how-much-price-landlord-policies/582898/
INFO:__main__:Getting metadata for https://www.citylab.com/equity/2019/02/berlin-germany-housing-rent-how-much-price-landlord-policies/582898/
 97%|█████████▋| 275/284 [09:13<00:07,  1.24it/s]INFO:__main__:Requesting https://www.mcsweeneys.net/articles/i-will-do-anything-to-end-homelessness-except-build-more-homes
INFO:__main__:Getting metadata for https://www.mcsweeneys.net/articles/i-will-do-anything-to-end-homelessness-except-build-more-homes
 97%|█████████▋| 276/284 [09:13<00:06,  1.33it/s]INFO:__main__:Requesting https://www.citylab.com/life/2014/04/ranking-most-sprawling-us-metro-areas-and-why-you-should-care/8782/
INFO:__main__:Getting metadata for https://www.citylab.com/life/2014/04/ranking-most-sprawling-us-metro-areas-and-why-you-should-care/8782/
 98%|█████████▊| 277/284 [09:14<00:04,  1.49it/s]INFO:__main__:Requesting https://www.youtube.com/watch?v=1Xq0VEwrSr8
INFO:__main__:Getting metadata for https://www.youtube.com/watch?v=1Xq0VEwrSr8
 98%|█████████▊| 278/284 [09:15<00:04,  1.28it/s]INFO:__main__:Requesting https://www.thedailybeast.com/stuck-in-new-york-city-private-school-wait-list-hell
INFO:__main__:Getting metadata for https://www.thedailybeast.com/stuck-in-new-york-city-private-school-wait-list-hell
 98%|█████████▊| 279/284 [09:15<00:03,  1.44it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Sin_tax
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Sin_tax
 99%|█████████▊| 280/284 [09:16<00:03,  1.24it/s]INFO:__main__:Requesting https://en.wikipedia.org/wiki/Land_value_tax
INFO:__main__:Getting metadata for https://en.wikipedia.org/wiki/Land_value_tax
 99%|█████████▉| 281/284 [09:18<00:03,  1.15s/it]INFO:__main__:Requesting https://www.scmagazine.com/home/security-news/intuit-the-company-behind-tax-preparation-software-turbotax-alerted-users-their-accounts-may-have-been-accessed-by-an-unauthorized-party/
INFO:__main__:Getting metadata for https://www.scmagazine.com/home/security-news/intuit-the-company-behind-tax-preparation-software-turbotax-alerted-users-their-accounts-may-have-been-accessed-by-an-unauthorized-party/
 99%|█████████▉| 282/284 [09:19<00:01,  1.09it/s]INFO:__main__:Requesting https://ttlc.intuit.com/questions/2902682-what-is-two-step-verification
INFO:__main__:Getting metadata for https://ttlc.intuit.com/questions/2902682-what-is-two-step-verification
100%|█████████▉| 283/284 [09:20<00:00,  1.10it/s]INFO:__main__:Requesting https://community.intuit.com/questions/1752343
INFO:__main__:Getting metadata for https://community.intuit.com/questions/1752343-will-the-new-oauth-banking-interface-be-fixed-to-allow-web-connect-downloads-from-third-party-delegate-users-like-bookkeepers-and-accountants-mostly-use
100%|██████████| 284/284 [09:23<00:00,  1.53s/it]
